Repository opendatahub-io/notebooks, pull requests merged in 2023-07, with the labels that each got.

#137 Update datascience pipeline run URL in Elyra
  jupyter/datascience/ubi9-python-3.9/Dockerfile
  jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
Labels: lgtm, approved

#142 Patch pipeline_run to also use pipeline_id for pipeline_version_id
  jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
Labels: approved

#153 fix Pipfile.lock exist in container
  base/c9s-python-3.9/Dockerfile
  base/ubi8-python-3.8/Dockerfile
  base/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved, ok-to-test

#144 dropped z stream from python version in notebook
  jupyter/datascience/ubi8-python-3.8/Dockerfile
  jupyter/datascience/ubi9-python-3.9/Dockerfile
  jupyter/minimal/ubi8-python-3.8/Dockerfile
  jupyter/minimal/ubi9-python-3.9/Dockerfile
  jupyter/pytorch/ubi8-python-3.8/Dockerfile
  jupyter/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/tensorflow/ubi8-python-3.8/Dockerfile
  jupyter/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/trustyai/ubi9-python-3.9/Dockerfile
Labels: approved
