Repository opendatahub-io/notebooks, pull requests merged in 2023-09, with the labels that each got.

#187 Add test cases for the PyTorch notebooks
  jupyter/pytorch/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#193 Add workflow to clean images after PR is merged
  .github/workflows/pr-merge-image-delete.yml
Labels: lgtm

#199 Fix UBI version used on particular places with regards the Pyton version
  Makefile
  jupyter/tensorflow/ubi9-python-3.9/Dockerfile
  runtimes/tensorflow/ubi9-python-3.9/Dockerfile
Labels: lgtm, needs-ok-to-test

#200 Use RHEL9 repository for UBI9 and CentOs Stream 9 Cuda images
  cuda/c9s-python-3.9/cuda.repo-x86_64
  cuda/ubi9-python-3.9/cuda.repo-x86_64
Labels: lgtm, ok-to-test

#186 Include notebook imagestream manifests to notebook repos
  .github/workflows/notebooks-digest-updater-upstream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/overlays/additional/README.md
  manifests/overlays/additional/code-server-notebook-imagestream.yaml
  manifests/overlays/additional/kustomization.yaml
  manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-notebook-imagestream.yaml
Labels: lgtm

#188 Add test cases for the TensorFlow notebooks
  jupyter/tensorflow/ubi8-python-3.8/test/test_notebooks.ipynb
  jupyter/tensorflow/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm

#189 Add tests for datascience notebooks
  jupyter/datascience/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm

#216 include missing images from cleanup code
  .github/workflows/pr-merge-image-delete.yml
Labels: lgtm, approved

#209 Upgrade trustyai notebook images to version 0.3.0
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#213 Add test case on the PyTorch notebook to convert a pytorch model to onnx format
  jupyter/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#224 Fix of UBI and Python version used for Jupyter TrustyAI image
  Makefile
Labels: lgtm, approved, ok-to-test

#226 Set $scheme correctly on vscode and rstudio on nginx configuration
  codeserver/c9s-python-3.9/nginx/httpconf/http.conf
  codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template
  codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
  rstudio/c9s-python-3.9/nginx/httpconf/http.conf
  rstudio/c9s-python-3.9/nginx/serverconf/proxy.conf.template
  rstudio/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
Labels: lgtm, approved

#222 adding elyra to imagestream
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved
