Repository opendatahub-io/notebooks, pull requests merged in 2023-10, with the labels that each got.

#214 include habana based notebook image installation
  Makefile
  README.md
  habana/1.10.0/ubi8-python-3.8/Dockerfile
  habana/1.10.0/ubi8-python-3.8/Pipfile
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
  habana/1.10.0/ubi8-python-3.8/README.md
  habana/1.10.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.10.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.10.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/1.11.0/ubi8-python-3.8/Dockerfile
  habana/1.11.0/ubi8-python-3.8/Pipfile
  habana/1.11.0/ubi8-python-3.8/Pipfile.lock
  habana/1.11.0/ubi8-python-3.8/README.md
  habana/1.11.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.11.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.11.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/1.9.0/ubi8-python-3.8/Dockerfile
  habana/1.9.0/ubi8-python-3.8/Pipfile
  habana/1.9.0/ubi8-python-3.8/Pipfile.lock
  habana/1.9.0/ubi8-python-3.8/README.md
  habana/1.9.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.9.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.9.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/README.md
Labels: lgtm, approved

#229 Integrate test notebook cases for both ubi8/ubi9 on various flavors of the notebooks
  Makefile
Labels: lgtm, approved

#233 Included habana based imagestream to the notebook manifests
  habana/README.md
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/overlays/additional/code-server-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-notebook-imagestream.yaml
Labels: approved

#242 Sync the commits from main branch to 2023a branch
  Makefile
  README.md
  habana/1.10.0/ubi8-python-3.8/Dockerfile
  habana/1.10.0/ubi8-python-3.8/Pipfile
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
  habana/1.10.0/ubi8-python-3.8/README.md
  habana/1.10.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.10.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.10.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/1.11.0/ubi8-python-3.8/Dockerfile
  habana/1.11.0/ubi8-python-3.8/Pipfile
  habana/1.11.0/ubi8-python-3.8/Pipfile.lock
  habana/1.11.0/ubi8-python-3.8/README.md
  habana/1.11.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.11.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.11.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/1.9.0/ubi8-python-3.8/Dockerfile
  habana/1.9.0/ubi8-python-3.8/Pipfile
  habana/1.9.0/ubi8-python-3.8/Pipfile.lock
  habana/1.9.0/ubi8-python-3.8/README.md
  habana/1.9.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.9.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.9.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/README.md
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/overlays/additional/code-server-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-notebook-imagestream.yaml
Labels: approved

#238 Adding piplock-renewal GH action on 2023b branch
  .github/workflows/piplock-renewal-2023b.yml
Labels: lgtm, approved

#250 Fix the pytorch image reference in main to commit e868e30
  manifests/base/params.env
Labels: lgtm, approved

#239 Re-adjust Auto Add Issues to Tracking boards
  .github/workflows/auto-add-issue-to-project.yml
Labels: lgtm, approved

#258 [tests] Allow to overwrite repository for testing script download
  Makefile
  README.md
Labels: lgtm, approved

#262 Add mesa-libGL on the base notebooks
  base/c9s-python-3.9/Dockerfile
  base/ubi8-python-3.8/Dockerfile
  base/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved

#265 Fix typo on tensorflow test notebook name
  jupyter/tensorflow/ubi8-python-3.8/test/test_notebook.ipynb
Labels: lgtm, approved

#266 Increase timeout on the makefile test recipe
  Makefile
Labels: lgtm, approved

#244 Add tests for TrustyAI Notebooks
  jupyter/trustyai/ubi8-python-3.8/test/income-biased.csv
  jupyter/trustyai/ubi8-python-3.8/test/income-unbiased.csv
  jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.9/test/income-biased.csv
  jupyter/trustyai/ubi9-python-3.9/test/income-unbiased.csv
  jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#245 Introduces basic JSON and YAML checks into this repository
  .github/workflows/auto-add-issue-to-project.yml
  .github/workflows/code-quality.yaml
  .github/workflows/notebooks-digest-updater-upstream.yaml
  .github/workflows/piplock-renewal-2023a.yml
  .github/workflows/piplock-renewal-2023b.yml
  .github/workflows/pr-merge-image-delete.yml
  base/anaconda-python-3.8/environment.yml
  ci/check-json.sh
  ci/yamllint-config.yaml
  codeserver/c9s-python-3.9/kustomize/base/pod.yaml
  jupyter/datascience/anaconda-python-3.8/environment.yml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.yaml
  manifests/overlays/additional/code-server-notebook-imagestream.yaml
  manifests/overlays/additional/kustomization.yaml
  manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-notebook-imagestream.yaml
  rstudio/c9s-python-3.9/kustomize/base/pod.yaml
  runtimes/datascience/ubi8-python-3.8/kustomize/base/kustomization.yaml
  runtimes/datascience/ubi8-python-3.8/kustomize/base/pod.yaml
  runtimes/datascience/ubi9-python-3.9/kustomize/base/kustomization.yaml
  runtimes/datascience/ubi9-python-3.9/kustomize/base/pod.yaml
  runtimes/minimal/ubi8-python-3.8/kustomize/base/kustomization.yaml
  runtimes/minimal/ubi8-python-3.8/kustomize/base/pod.yaml
  runtimes/minimal/ubi9-python-3.9/kustomize/base/kustomization.yaml
  runtimes/minimal/ubi9-python-3.9/kustomize/base/pod.yaml
  runtimes/pytorch/ubi8-python-3.8/kustomize/base/kustomization.yaml
  runtimes/pytorch/ubi8-python-3.8/kustomize/base/pod.yaml
  runtimes/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  runtimes/pytorch/ubi9-python-3.9/kustomize/base/pod.yaml
  runtimes/tensorflow/ubi8-python-3.8/kustomize/base/kustomization.yaml
  runtimes/tensorflow/ubi8-python-3.8/kustomize/base/pod.yaml
  runtimes/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  runtimes/tensorflow/ubi9-python-3.9/kustomize/base/pod.yaml
Labels: lgtm, approved

#268 Add name for the notebook digest github action
  .github/workflows/notebooks-digest-updater-upstream.yaml
Labels: lgtm, approved

#272 remove depreciated bases kustomize feature
  manifests/overlays/additional/kustomization.yaml
Labels: lgtm, approved, ok-to-test

#271 Fix and improve CI unit test workaround
  Makefile
Labels: lgtm, approved

#274 Adding test for trustyai notebook
  jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#281 Update docs in favor of the 2023b release
  docs/developer-guide.md
  docs/user-guide.md
  docs/workbench-imagestreams.md
  docs/workbenches.md
Labels: lgtm, approved

#286 chore: update runtime images with the commit: 34c3405
  jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Labels: lgtm, approved

#284 updating package versions for notebook test
  jupyter/datascience/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/minimal/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/minimal/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/tensorflow/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/tensorflow/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#270 Update imagestreams with new 2023b images
  .github/workflows/notebooks-digest-updater-upstream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/overlays/additional/code-server-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-notebook-imagestream.yaml
Labels: lgtm, approved

#289 Shift the n version to n-1 to fix the digest updater to fetch the correct image
  manifests/base/params.env
Labels: lgtm, approved

#291 fix: missing recommended annotation for TrustyAI
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved
