Repository opendatahub-io/notebooks, pull requests merged in 2024-11, with the labels that each got.

#757 Updated odh-elyra from 4.1.1 to 4.2.0
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#760 RHOAIENG-15242: ref(manifests): add some newlines and indentation into the json strings with package version information
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-pytorch-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved

#759 Remove of the CUDA RPM repository definition for arm arch
  cuda/ubi9-python-3.11/cuda.repo-arm64
Labels: lgtm, approved

#765 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.23.1
  intel/runtimes/ml/ubi9-python-3.11/Pipfile
  intel/runtimes/ml/ubi9-python-3.11/Pipfile.lock
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.11/Pipfile
  jupyter/intel/ml/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#764 Update annotations for codeflare-sdk and odh-elyra in the ImageStreams annotations
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved

#771 [RHOAIENG-15710] fix the version of codeflare-sdk shown for 2024.1
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved

#773 Fix image reference for vscode image
  manifests/base/params.env
Labels: lgtm, approved

#755 RHOAIENG-15152: feat(codeserver/e2e): add initial playwright e2e test project skeleton
  ci/yamllint-config.yaml
  tests/browser/.gitignore
  tests/browser/README.md
  tests/browser/package.json
  tests/browser/playwright.config.ts
  tests/browser/pnpm-lock.yaml
  tests/containers/__init__.py
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan

#772 RHOAIENG-11156: Add a loading spinner to JupyterLab index page
  jupyter/intel/ml/ubi9-python-3.11/Dockerfile
  jupyter/intel/ml/ubi9-python-3.11/utils/addons/apply.sh
  jupyter/intel/ml/ubi9-python-3.11/utils/addons/partial-body.html
  jupyter/intel/ml/ubi9-python-3.11/utils/addons/partial-head.html
  jupyter/intel/ml/ubi9-python-3.9/Dockerfile
  jupyter/intel/ml/ubi9-python-3.9/utils/addons/apply.sh
  jupyter/intel/ml/ubi9-python-3.9/utils/addons/partial-body.html
  jupyter/intel/ml/ubi9-python-3.9/utils/addons/partial-head.html
  jupyter/intel/pytorch/ubi9-python-3.11/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.11/utils/addons/apply.sh
  jupyter/intel/pytorch/ubi9-python-3.11/utils/addons/partial-body.html
  jupyter/intel/pytorch/ubi9-python-3.11/utils/addons/partial-head.html
  jupyter/intel/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.9/utils/addons/apply.sh
  jupyter/intel/pytorch/ubi9-python-3.9/utils/addons/partial-body.html
  jupyter/intel/pytorch/ubi9-python-3.9/utils/addons/partial-head.html
  jupyter/intel/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.11/utils/addons/apply.sh
  jupyter/intel/tensorflow/ubi9-python-3.11/utils/addons/partial-body.html
  jupyter/intel/tensorflow/ubi9-python-3.11/utils/addons/partial-head.html
  jupyter/intel/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.9/utils/addons/apply.sh
  jupyter/intel/tensorflow/ubi9-python-3.9/utils/addons/partial-body.html
  jupyter/intel/tensorflow/ubi9-python-3.9/utils/addons/partial-head.html
  jupyter/minimal/ubi9-python-3.11/Dockerfile
  jupyter/minimal/ubi9-python-3.11/utils/addons/apply.sh
  jupyter/minimal/ubi9-python-3.11/utils/addons/partial-body.html
  jupyter/minimal/ubi9-python-3.11/utils/addons/partial-head.html
  jupyter/minimal/ubi9-python-3.9/Dockerfile
  jupyter/minimal/ubi9-python-3.9/utils/addons/apply.sh
  jupyter/minimal/ubi9-python-3.9/utils/addons/partial-body.html
  jupyter/minimal/ubi9-python-3.9/utils/addons/partial-head.html
Labels: lgtm, approved

#774 RHOAIENG-15152: test(tests/browser): add playwright test for starting code-server
  .github/workflows/build-notebooks-TEMPLATE.yaml
  tests/browser/playwright.config.ts
  tests/browser/tests/codeserver.spec.ts
  tests/browser/tests/models/codeserver.ts
  tests/browser/tests/testcontainers.ts
  tests/browser/tests/utils.ts
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan

#777 RHOAIENG-16076: tests(gha): pre-pull trivy vulnerabilities db to prevent failures to download later
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan

#781 RHOAIENG-16076: tests(gha): mount the lvm volume with performance flags
  ci/cached-builds/gha_lvm_overlay.sh
Labels: lgtm, approved, tide/merge-method-squash

#779 RHOAIENG-16149: chore(Makefile) download arch-appropriate version of kubectl
  Makefile
Labels: lgtm, approved, tide/merge-method-squash

#778 RHOAIENG-16149: chore(Makefile): implement advice from avis-hansson.com/p/make/
  Makefile
Labels: lgtm, approved, tide/merge-method-squash

#782 RHOAIENG-16076: tests(gha): change to using rootful podman, so that we can share `containers/storage` with cri-o later
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/containers.conf
  ci/cached-builds/homebrew.podman.service
  ci/cached-builds/podman.service
  ci/cached-builds/podman.socket
  ci/cached-builds/registries.conf
  ci/cached-builds/storage.conf
Labels: lgtm, approved, tide/merge-method-squash

#761 Remove requirments-elyra.txt from the code base
  Makefile
  runtimes/datascience/ubi9-python-3.11/kustomize/base/kustomization.yaml
  runtimes/datascience/ubi9-python-3.11/kustomize/base/pod.yaml
  runtimes/datascience/ubi9-python-3.11/kustomize/base/requirements-elyra.txt
  runtimes/datascience/ubi9-python-3.11/utils/requirements-elyra.txt
  runtimes/minimal/ubi9-python-3.11/kustomize/base/kustomization.yaml
  runtimes/minimal/ubi9-python-3.11/kustomize/base/pod.yaml
  runtimes/minimal/ubi9-python-3.11/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi9-python-3.11/utils/requirements-elyra.txt
  runtimes/pytorch/ubi9-python-3.11/kustomize/base/kustomization.yaml
  runtimes/pytorch/ubi9-python-3.11/kustomize/base/pod.yaml
  runtimes/pytorch/ubi9-python-3.11/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi9-python-3.11/utils/requirements-elyra.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/kustomize/base/kustomization.yaml
  runtimes/rocm-pytorch/ubi9-python-3.11/kustomize/base/pod.yaml
  runtimes/rocm-pytorch/ubi9-python-3.11/kustomize/base/requirements-elyra.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/utils/requirements-elyra.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/kustomize/base/kustomization.yaml
  runtimes/rocm-tensorflow/ubi9-python-3.11/kustomize/base/pod.yaml
  runtimes/rocm-tensorflow/ubi9-python-3.11/kustomize/base/requirements-elyra.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/utils/requirements-elyra.txt
  runtimes/tensorflow/ubi9-python-3.11/kustomize/base/kustomization.yaml
  runtimes/tensorflow/ubi9-python-3.11/kustomize/base/pod.yaml
  runtimes/tensorflow/ubi9-python-3.11/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi9-python-3.11/utils/requirements-elyra.txt
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan

#783 RHOAIENG-16076: tests(gha): install a cri-o backed kubernetes for running Makefile tests
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/11-crio-ipv4-bridge.conflist
  ci/cached-builds/crio.conf
  ci/cached-builds/has_tests.py
  ci/cached-builds/kubeadm.yaml
Labels: lgtm, approved, tide/merge-method-squash

#785 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.24.0
  intel/runtimes/ml/ubi9-python-3.11/Pipfile
  intel/runtimes/ml/ubi9-python-3.11/Pipfile.lock
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.11/Pipfile
  jupyter/intel/ml/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm

#786 Update codeflare-sdk version on the imagestream files
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved

#775 RHOAIENG-16076: tests(gha): run Makefile tests on opendatahub-io/notebooks Github Actions
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  ci/cached-builds/make_test.py
  jupyter/rocm/pytorch/ubi9-python-3.11/kustomize/base/kustomization.yaml
  jupyter/rocm/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.11/kustomize/base/kustomization.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan
