Repository opendatahub-io/notebooks, pull requests merged in 2024-01, with the labels that each got.

#379 Add documentation on how you can install db client on code-server
  docs/Incorporate-database-cients-on-code-server.md
Labels: lgtm, approved

#382 Move vscode server imagestream and configurations to 2023b branch
  manifests/base/code-server-notebook-imagestream.yaml.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
Labels: lgtm, approved

#383 Sync 2023b with the change from main for sprint 2.6 feature freeze
  .github/workflows/notebooks-digest-updater-upstream.yaml
  base/anaconda-python-3.8/Dockerfile
  base/anaconda-python-3.8/environment.yml
  codeserver/ubi9-python-3.9/Dockerfile
  codeserver/ubi9-python-3.9/Pipfile
  codeserver/ubi9-python-3.9/Pipfile.lock
  codeserver/ubi9-python-3.9/run-code-server.sh
  codeserver/ubi9-python-3.9/utils/ms-toolsai.jupyter-keymap-1.1.2.vsix
  codeserver/ubi9-python-3.9/utils/ms-toolsai.vscode-jupyter-cell-tags-0.1.8.vsix
  codeserver/ubi9-python-3.9/utils/ms-toolsai.vscode-jupyter-slideshow-0.1.5.vsix
  docs/Incorporate-database-cients-on-code-server.md
  docs/workbenches.md
  jupyter/datascience/anaconda-python-3.8/environment.in
  jupyter/datascience/anaconda-python-3.8/environment.yml
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/commit.env
  manifests/base/commit.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
  manifests/overlays/additional/README.md
  manifests/overlays/additional/code-server-notebook-imagestream.yaml
  manifests/overlays/additional/kustomization.yaml
  manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
  manifests/overlays/additional/rstudio-notebook-imagestream.yaml
Labels: lgtm, rhods-2.6

#384 Fix: update the typo of ubi9 on trusty ai notebook
  .github/workflows/notebooks-digest-updater-upstream.yaml
  jupyter/datascience/anaconda-python-3.8/environment.yml
  jupyter/trustyai/ubi8-python-3.8/Dockerfile
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
Labels: lgtm, approved

#389 Use Titlecase for annotation naming
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved

#390 Fix: Use code-server reference in all the files
  .github/ISSUE_TEMPLATE/bug_report.md
  Makefile
  README.md
  codeserver/c9s-python-3.9/Dockerfile
  codeserver/c9s-python-3.9/nginx/api/kernels/access.cgi
  codeserver/c9s-python-3.9/nginx/httpconf/http.conf
  codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template
  codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
  codeserver/c9s-python-3.9/run-code-server.sh
  codeserver/ubi9-python-3.9/Dockerfile
  codeserver/ubi9-python-3.9/nginx/api/kernels/access.cgi
  codeserver/ubi9-python-3.9/nginx/httpconf/http.conf
  codeserver/ubi9-python-3.9/nginx/serverconf/proxy.conf.template
  codeserver/ubi9-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
  codeserver/ubi9-python-3.9/run-code-server.sh
  docs/Incorporate-database-cients-on-code-server.md
  docs/workbenches.md
  manifests/base/code-server-notebook-imagestream.yaml
  rstudio/c9s-python-3.9/Dockerfile
  rstudio/c9s-python-3.9/nginx/api/kernels/access.cgi
Labels: lgtm
