Repository opendatahub-io/notebooks, pull requests merged in 2024-12, with the labels that each got.

#793 Remove Habana references from docs
  docs/developer-guide.md
  docs/workbench-imagestreams.md
  docs/workbenches.md
  manifests/base/README.md
Labels: lgtm, approved

#792 RHOAIENG-11274: chore(Makefile): widen the container build context to the whole repo, so we can start reusing code between images in the future
  .dockerignore
  Makefile
  base/c9s-python-3.11/Dockerfile
  base/c9s-python-3.9/Dockerfile
  base/ubi9-python-3.11/Dockerfile
  base/ubi9-python-3.9/Dockerfile
  codeserver/ubi9-python-3.11/Dockerfile
  codeserver/ubi9-python-3.9/Dockerfile
  cuda/c9s-python-3.11/Dockerfile
  cuda/c9s-python-3.9/Dockerfile
  cuda/ubi9-python-3.11/Dockerfile
  cuda/ubi9-python-3.9/Dockerfile
  intel/base/gpu/ubi9-python-3.11/Dockerfile
  intel/base/gpu/ubi9-python-3.9/Dockerfile
  intel/runtimes/ml/ubi9-python-3.11/Dockerfile
  intel/runtimes/ml/ubi9-python-3.9/Dockerfile
  intel/runtimes/pytorch/ubi9-python-3.11/Dockerfile
  intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
  intel/runtimes/tensorflow/ubi9-python-3.11/Dockerfile
  intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/datascience/ubi9-python-3.11/Dockerfile
  jupyter/datascience/ubi9-python-3.9/Dockerfile
  jupyter/intel/ml/ubi9-python-3.11/Dockerfile
  jupyter/intel/ml/ubi9-python-3.9/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.11/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/minimal/ubi9-python-3.11/Dockerfile
  jupyter/minimal/ubi9-python-3.9/Dockerfile
  jupyter/pytorch/ubi9-python-3.11/Dockerfile
  jupyter/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/trustyai/ubi9-python-3.11/Dockerfile
  jupyter/trustyai/ubi9-python-3.9/Dockerfile
  rocm/ubi9-python-3.11/Dockerfile
  rocm/ubi9-python-3.9/Dockerfile
  rstudio/c9s-python-3.11/Dockerfile
  rstudio/c9s-python-3.9/Dockerfile
  runtimes/datascience/ubi9-python-3.11/Dockerfile
  runtimes/datascience/ubi9-python-3.9/Dockerfile
  runtimes/minimal/ubi9-python-3.11/Dockerfile
  runtimes/minimal/ubi9-python-3.9/Dockerfile
  runtimes/pytorch/ubi9-python-3.11/Dockerfile
  runtimes/pytorch/ubi9-python-3.9/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Dockerfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Dockerfile
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile
  runtimes/tensorflow/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved, tide/merge-method-squash

#799 NO-JIRA: fix selftest, need to use gmake on macOS
  ci/cached-builds/gha_pr_changed_files.py
Labels: lgtm, approved, tide/merge-method-squash

#800 RHOAIENG-16517: chore(tests): add new changed-files-rebuild helper for GitHub Actions PRs
  .github/workflows/build-notebooks-pr.yaml
  Makefile
  ci/cached-builds/gha_pr_changed_files.py
  scripts/README.md
  scripts/buildinputs/README.md
  scripts/buildinputs/buildinputs.go
  scripts/buildinputs/buildinputs_test.go
  scripts/buildinputs/dockerfile.go
  scripts/buildinputs/go.mod
  scripts/buildinputs/go.sum
  scripts/buildinputs/utils.go
Labels: lgtm, approved, tide/merge-method-squash

#803 RHOAIENG-16517: chore(tests): add sandboxing so that Dockerfile builds can only access files we know they access
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  ci/cached-builds/gha_lvm_overlay.sh
  poetry.lock
  pyproject.toml
  scripts/sandbox.py
  scripts/sandbox_tests.py
Labels: lgtm, approved, tide/merge-method-squash

#805 Update Piplock Renewal GitHub Action
  .github/workflows/piplock-renewal-2023a.yml
  .github/workflows/piplock-renewal-2023b.yml
  .github/workflows/piplock-renewal-2024a.yml
  .github/workflows/piplock-renewal-main.yml
  .github/workflows/piplock-renewal.yaml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: lgtm, approved

#808 RHOAIENG-16403: chore(Makefile): remove the now-unnecessary trailing slash (`\s*;?\s*\\$`)
  Makefile
Labels: lgtm, approved, tide/merge-method-squash

#809 NO-JIRA: chore(.editorconfig): introduce `.editorconfig` file for the project
  .editorconfig
Labels: lgtm, approved, tide/merge-method-squash

#811 Make the pipfile renewal to work when cron firing
  .github/workflows/piplock-renewal.yaml
Labels: lgtm, approved

#807 RHOAIENG-16520, RHOAIENG-11807, RHOAIENG-16955: update setuptools to 70.0.0 for CVE fixes
  base/c9s-python-3.11/Pipfile
  base/c9s-python-3.11/Pipfile.lock
  base/c9s-python-3.9/Pipfile
  base/c9s-python-3.9/Pipfile.lock
  base/ubi9-python-3.9/Pipfile
  base/ubi9-python-3.9/Pipfile.lock
  codeserver/ubi9-python-3.11/Pipfile
  codeserver/ubi9-python-3.11/Pipfile.lock
  codeserver/ubi9-python-3.9/Pipfile
  codeserver/ubi9-python-3.9/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.11/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi9-python-3.11/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved, tide/merge-method-squash

#816 NO-JIRA: chore(gha): run code-server playwright tests for pushes (and scheduled run) as well
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved

#818 NO-ISSUE: chore(owners): add myself as reviewer/approver
  OWNERS
Labels: lgtm, approved

#815 [2024a] Cherry-pick: RHOAIENG-15393: update piplock renewal gh action
  .github/workflows/piplock-renewal-2023a.yml
  .github/workflows/piplock-renewal-2023b.yml
  .github/workflows/piplock-renewal-2024a.yml
  .github/workflows/piplock-renewal.yaml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: lgtm, approved, tide/merge-method-squash

#813 [2024a] NO-JIRA: bring in CI fixes from the `main` branch into the `2024a` branch
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  ci/cached-builds/11-crio-ipv4-bridge.conflist
  ci/cached-builds/containers.conf
  ci/cached-builds/crio.conf
  ci/cached-builds/gha_lvm_overlay.sh
  ci/cached-builds/gha_pr_changed_files.py
  ci/cached-builds/has_tests.py
  ci/cached-builds/homebrew.podman.service
  ci/cached-builds/kubeadm.yaml
  ci/cached-builds/make_test.py
  ci/cached-builds/podman.service
  ci/cached-builds/podman.socket
  ci/cached-builds/registries.conf
  ci/cached-builds/storage.conf
  ci/yamllint-config.yaml
  jupyter/rocm/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  tests/browser/.gitignore
  tests/browser/README.md
  tests/browser/package.json
  tests/browser/playwright.config.ts
  tests/browser/pnpm-lock.yaml
  tests/browser/tests/codeserver.spec.ts
  tests/browser/tests/models/codeserver.ts
  tests/browser/tests/testcontainers.ts
  tests/browser/tests/utils.ts
  tests/containers/__init__.py
Labels: lgtm, approved

#820 [2024a] Update pipfile renewal for 2024a branch
  .github/workflows/piplock-renewal.yaml
Labels: lgtm, approved

#819 NO-JIRA: chore(tests): use gmake on macOS
  tests/test_main.py
Labels: lgtm, approved

#810 Pin `jupyterlab` package to version `4.2.6`
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/minimal/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile
Labels: lgtm, approved

#824 [2024a] RHOAIENG-16520, RHOAIENG-11807, RHOAIENG-16955: update setuptools to 70.0.0 for CVE fixes
  base/c9s-python-3.9/Pipfile
  base/c9s-python-3.9/Pipfile.lock
  base/ubi8-python-3.8/Pipfile
  base/ubi8-python-3.8/Pipfile.lock
  base/ubi9-python-3.9/Pipfile
  base/ubi9-python-3.9/Pipfile.lock
  codeserver/ubi9-python-3.9/Pipfile
  codeserver/ubi9-python-3.9/Pipfile.lock
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi8-python-3.8/Pipfile
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved, tide/merge-method-squash

#797 RHOAIENG-16604: feat(RStudio): grab proxy-related env vars from container env context and set them in R default environment
  rstudio/c9s-python-3.11/run-rstudio.sh
Labels: lgtm, approved, ok-to-test

#798 RHOAIENG-17256: install necessary base OS package to make Knit rendering of R markup to PDF possible
  rstudio/c9s-python-3.11/Dockerfile
Labels: lgtm, approved, ok-to-test
