Repository opendatahub-io/notebooks, pull requests merged in 2024-07, with the labels that each got.

#600 Add daily check for vulnerability issues using Trivy
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/build-notebooks.yaml
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/trivy-markdown.tpl
Labels: lgtm, approved

#605 ci: start podman.socket and pass it to trivy to avoid unnecessary pulls
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/homebrew.podman.service
Labels: lgtm, approved, tide/merge-method-squash

#601 ci: implement ghcr.io expiration for images and cache layers
  .github/workflows/purge-ghcr.yaml
Labels: lgtm, approved, tide/merge-method-squash

#602 ci: get a list of changed files using git diff instead of GitHub APIv4
  .github/workflows/build-notebooks-pr.yaml
  .github/workflows/build-notebooks.yaml
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/gha_pr_changed_files.py
Labels: lgtm, approved

#607 RHOAIENG-9473: Optionally enable Trivy for pull requests
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/build-notebooks-pr.yaml
Labels: lgtm, approved

#612 ci: use a smarter `git status` check for uncommitted files
  .github/workflows/code-quality.yaml
Labels: lgtm, approved, tide/merge-method-squash

#613 RHOAIENG-1751: Bump `jinja2` lib to `3.1.4`
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/ml/ubi9-python-3.9/utils/requirements-elyra.txt
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.lock.gpu
  intel/runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/pytorch/ubi9-python-3.9/utils/requirements-elyra.txt
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/tensorflow/ubi9-python-3.9/utils/requirements-elyra.txt
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/datascience/ubi8-python-3.8/utils/requirements-elyra.txt
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/datascience/ubi9-python-3.9/utils/requirements-elyra.txt
  runtimes/minimal/ubi8-python-3.8/Pipfile
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi8-python-3.8/utils/requirements-elyra.txt
  runtimes/minimal/ubi9-python-3.9/Pipfile
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi9-python-3.9/utils/requirements-elyra.txt
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi8-python-3.8/utils/requirements-elyra.txt
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi9-python-3.9/utils/requirements-elyra.txt
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi8-python-3.8/utils/requirements-elyra.txt
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi9-python-3.9/utils/requirements-elyra.txt
Labels: lgtm, approved, trivy-scan

#614 Enable all severities on the Trivy daily report
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved

#608 RHOAIENG-1249: Bump `requests` lib to `2.31.0`
  intel/runtimes/ml/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/datascience/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/datascience/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
Labels: lgtm, approved

#616 Update trusty from 0.3 to 0.6 to fix vulnerabilities
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#615 Update of the TrustyAI version in the Jupyter TrustyAI notebook
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved

#619 [2023a] RHOAIENG-8299: Fix CentOS Stream 8 download location
  habana/1.10.0/ubi8-python-3.8/Dockerfile
  habana/1.11.0/ubi8-python-3.8/Dockerfile
  habana/1.9.0/ubi8-python-3.8/Dockerfile
Labels: lgtm, approved

#618 RHOAIENG-9741: Add Tensorflow/PyTorch version compatibility files
  ci/version-compatibility/pytorch.json
  ci/version-compatibility/tensorflow.json
Labels: lgtm, approved

#433 ci: initial implementation of top-level pytest tests
  .github/workflows/code-quality.yaml
  README.md
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/__init__.py
  tests/test_main.py
Labels: lgtm, approved, ok-to-test, tide/merge-method-squash

#611 Update OWNERS file with adding more approvers
  CONTRIBUTING.md
  OWNERS
Labels: lgtm, approved

#622 Show `podman images` information on the CI
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved

#621 RHOAIENG-9168: Remove unused images from notebooks repo
  .github/workflows/build-notebooks.yaml
  Makefile
  habana/1.11.0/ubi8-python-3.8/Dockerfile
  habana/1.11.0/ubi8-python-3.8/Pipfile
  habana/1.11.0/ubi8-python-3.8/Pipfile.lock
  habana/1.11.0/ubi8-python-3.8/README.md
  habana/1.11.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.11.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.11.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/1.9.0/ubi8-python-3.8/Dockerfile
  habana/1.9.0/ubi8-python-3.8/Pipfile
  habana/1.9.0/ubi8-python-3.8/Pipfile.lock
  habana/1.9.0/ubi8-python-3.8/README.md
  habana/1.9.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.9.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.9.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
  habana/README.md
  jupyter/trustyai/ubi8-python-3.8/Dockerfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/kustomize/base/kustomization.yaml
  jupyter/trustyai/ubi8-python-3.8/kustomize/base/service.yaml
  jupyter/trustyai/ubi8-python-3.8/kustomize/base/statefulset.yaml
  jupyter/trustyai/ubi8-python-3.8/test/income-biased.csv
  jupyter/trustyai/ubi8-python-3.8/test/income-unbiased.csv
  jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb
Labels: lgtm, approved

#627 feat(ci): add helpful error when check-generated-code gha workflow fails
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/code-quality.yaml
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/gha_lvm_overlay.sh
  ci/generate_code.sh
Labels: lgtm, approved, tide/merge-method-squash

#625 [2023a] Update OWNERS file
  OWNERS
Labels: lgtm, approved

#624 [2023b] Update OWNERS file
  OWNERS
Labels: lgtm, approved

#620 Switch base image to UBI for AMD rocm install
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/build-notebooks.yaml
  Makefile
  amd/c9s-python-3.9/Dockerfile
  ci/cached-builds/gen_gha_matrix_jobs.py
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/rocm/pytorch/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/rocm/pytorch/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/rocm/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.9/test/test_notebook.ipynb
  rocm/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved, trivy-scan

#632 fix(selftests): update target names in selftests for github action scripting
  ci/cached-builds/gen_gha_matrix_jobs.py
Labels: lgtm, approved, tide/merge-method-squash

#634 Combine `RUN` commands to reduce rocm image size
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved

#626 Incorporate rocm-pytorch and rocm-tensorflow runtime images
  .github/workflows/build-notebooks.yaml
  Makefile
  runtimes/rocm-pytorch/ubi9-python-3.9/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  runtimes/rocm-pytorch/ubi9-python-3.9/kustomize/base/pod.yaml
  runtimes/rocm-pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/rocm-pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-pytorch/ubi9-python-3.9/utils/pip.conf
  runtimes/rocm-pytorch/ubi9-python-3.9/utils/requirements-elyra.txt
  runtimes/rocm-tensorflow/ubi9-python-3.9/Dockerfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  runtimes/rocm-tensorflow/ubi9-python-3.9/kustomize/base/pod.yaml
  runtimes/rocm-tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/rocm-tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-tensorflow/ubi9-python-3.9/utils/pip.conf
  runtimes/rocm-tensorflow/ubi9-python-3.9/utils/requirements-elyra.txt
Labels: lgtm, approved, tide/merge-method-squash

#630 Pinned down jupyter-server-proxy for cve fixes
  habana/1.10.0/ubi8-python-3.8/Pipfile
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
Labels: lgtm, approved, do-not-merge/hold

#637 chore(ci): Run Trivy scan `fs` instead of `image` for rocm+pytorch image due to resource constraints
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved
