Repository opendatahub-io/notebooks, pull requests merged in 2024-06, with the labels that each got.

#547 Run the static code checks on push and when manually triggered
  .github/workflows/code-quality.yaml
Labels: lgtm, approved

#544 Intel AI Tools Images rebased
  Makefile
  intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
  intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/intel/ml/ubi9-python-3.9/.patch_sklearn.py
  jupyter/intel/ml/ubi9-python-3.9/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.9/oneAPI.repo
  jupyter/intel/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.9/oneAPI.repo
Labels: lgtm, approved, ok-to-test

#553 RHOAIENG-8255: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location
  codeserver/ubi9-python-3.9/Dockerfile
  rstudio/c9s-python-3.9/Dockerfile
Labels: lgtm, approved

#554 RHOAIENG-8299: Fix CentOS Stream 8 download location
  habana/1.10.0/ubi8-python-3.8/Dockerfile
  habana/1.11.0/ubi8-python-3.8/Dockerfile
  habana/1.13.0/ubi8-python-3.8/Dockerfile
  habana/1.9.0/ubi8-python-3.8/Dockerfile
Labels: lgtm, approved

#543 RHOAIENG-7525: Build opendatahub-io/notebooks in GitHub Action with caching
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/build-notebooks-pr.yaml
  .github/workflows/build-notebooks.yaml
  .github/workflows/code-quality.yaml
  Makefile
  ci/cached-builds/containers.conf
  ci/cached-builds/dev_null_container_registry.go
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/insecure_localhost_registry.conf
  ci/cached-builds/storage.conf
Labels: lgtm, approved, ok-to-test

#556 Fix issue with Run and Debug on code-server workbench
  codeserver/ubi9-python-3.9/Dockerfile
  codeserver/ubi9-python-3.9/run-code-server.sh
Labels: lgtm, approved

#552 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.16.3
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#561 Add new team members on the reviewer list
  OWNERS
Labels: lgtm, approved

#570 [2023b] RHOAIENG-8740 Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location (#569)
  codeserver/c9s-python-3.9/Dockerfile
Labels: lgtm, approved

#571 [2023b] RHOAIENG-8299: Fix CentOS Stream 8 download location
  habana/1.10.0/ubi8-python-3.8/Dockerfile
  habana/1.11.0/ubi8-python-3.8/Dockerfile
  habana/1.9.0/ubi8-python-3.8/Dockerfile
Labels: lgtm, approved

#572 Update pytorch image to torch version from 2.0 to 2.2 on 2023b release
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#573 Update annotations for torch package on n-1 (2023b) version
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
Labels: lgtm, approved

#567 [CI] Enhance params env check script
  .github/workflows/params-env.yaml
  ci/check-params-env.sh
  ci/check-runtime-images.sh
Labels: lgtm, approved

#578 Upgrade odh-elyra 3.16.7 for run_url update
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Labels: lgtm

#589 Add new GitHub workflow to sync branches through PR
  .github/workflows/sync-branches-through-pr.yml
Labels: lgtm, approved

#558 Limit PR checks to build only the modified images
  .github/workflows/build-notebooks-pr.yaml
  Makefile
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/gha_pr_changed_files.py
Labels: lgtm, approved, tide/merge-method-squash

#566 [GHA] digest updater workflow fixes and updates
  .github/workflows/notebooks-digest-updater-upstream.yaml
  .github/workflows/runtimes-digest-updater-upstream.yaml
  ci/security-scan/quay_security_analysis.py
Labels: lgtm, approved, ok-to-test

#577 ci: increase available disk space for GHA container image builds
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/gha_lvm_overlay.bash
  ci/cached-builds/storage.conf
Labels: lgtm, approved, tide/merge-method-squash

#587 feat(RHOAIENG-8298): Replace `spawn-fcgi` with `supervisord` in code-server and r-studio server
  codeserver/ubi9-python-3.9/Dockerfile
  codeserver/ubi9-python-3.9/run-code-server.sh
  codeserver/ubi9-python-3.9/supervisord/supervisord.conf
  rstudio/c9s-python-3.9/Dockerfile
  rstudio/c9s-python-3.9/run-rstudio.sh
  rstudio/c9s-python-3.9/supervisord/supervisord.conf
Labels: lgtm, approved

#557 Setup build images for Pytorch & Tensorflow with base ROCm image
  Makefile
  jupyter/amd/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/amd/pytorch/ubi9-python-3.9/Pipfile
  jupyter/amd/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/amd/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/amd/pytorch/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/amd/pytorch/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/amd/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/amd/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/amd/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/amd/tensorflow/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/amd/tensorflow/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/amd/tensorflow/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved, tide/merge-method-squash

#595 Upgrade codeflare-sdk with the latest 0.16.4
  jupyter/amd/pytorch/ubi9-python-3.9/Pipfile
  jupyter/amd/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: approved
