Repository opendatahub-io/notebooks, pull requests merged in 2024-05, with the labels that each got.

#517 Update trustyAI test_notebooks
  Makefile
  jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#518 Allow runtime script to cp the package from bin to Rpackage default path
  rstudio/c9s-python-3.9/run-rstudio.sh
Labels: lgtm, approved

#524 Fix/Unify naming of the variables used for the images
  .github/workflows/notebooks-digest-updater-upstream.yaml
  ci/check-params-env.sh
  ci/security-scan/quay_security_analysis.py
  ci/security-scan/weekly_commit_ids.env
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
Labels: lgtm, approved

#523 Update expected values for the Habana 2024a and 2023b images in CI
  ci/check-params-env.sh
Labels: lgtm, approved

#507 Adding Dockerfile for AMD based on Centos9
  amd/c9s-python-3.9/Dockerfile
Labels: lgtm, approved

#531 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.16.1
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved, ok-to-test

#522 Extend CI image check to also runtime images
  .github/workflows/params-env.yaml
  ci/check-runtime-images.sh
Labels: lgtm, approved

#534 Upgrade odh-elyra 3.16.6 that includes pod toleration, label and anno…
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#519 Specify version id to 9.3 on intel repository
  intel/base/gpu/ubi9-python-3.9/Dockerfile
Labels: lgtm

#546 Update ODH notebooks maintainer list
  OWNERS
Labels: lgtm, approved

#542 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.16.2
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#545 [CI] Add `kubectl kustomize` run to check our manifests definition
  .github/workflows/code-quality.yaml
Labels: lgtm

#525 Check commit id from commit.env file for the images in params.env file
  .github/workflows/params-env.yaml
  ci/check-params-env.sh
Labels: lgtm, approved

#549 [2024a] sync the 2024a release branch with the main branch
  .github/workflows/code-quality.yaml
  .github/workflows/params-env.yaml
  OWNERS
  ci/check-params-env.sh
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  manifests/base/commit.env
  manifests/base/params.env
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: approved

#548 [2024a] sync the 2024a release branch with the main branch
  .github/workflows/code-quality.yaml
  .github/workflows/params-env.yaml
  OWNERS
  ci/check-params-env.sh
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  manifests/base/commit.env
  manifests/base/params.env
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: needs-rebase
