Repository opendatahub-io/notebooks, pull requests merged in 2024-10, with the labels that each got.

#709 chores: set the python 3.11 content for refresh-pipfile-lock cmd in Makefile
  Makefile
Labels: lgtm, approved

#715 Updated odh-elyra from 4.0.0.dev1 to 4.0.0rc0
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/setup-elyra.sh
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#724 Updated odh-elyra from 4.0.0rc0 to 4.0.0
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#725 Upgrade Notebook with codeflare-sdk version 0.21.1
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#726 Updated odh-elyra from 4.0.0 to 4.0.1
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#722 Patch TensorFlow Pipfile to download its own cuda version GPU
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#721 Updated the notebook manifests with 2024b image reference
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
Labels: lgtm, approved

#716 [RHOAIENG-12621] Update the updater github action to the latest branch
  .github/workflows/notebooks-digest-updater-upstream.yaml
  .github/workflows/runtimes-digest-updater-upstream.yaml
Labels: lgtm, approved, tide/merge-method-squash

#733 Updated odh-elyra from 4.0.2 to 4.0.3
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#735 Set the manifests in right order with minor fixes
  manifests/base/README.md
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
Labels: lgtm, tide/merge-method-squash

#737 Fix the validation ci check with latest changes
  ci/check-params-env.sh
Labels: lgtm, approved

#738 Remove unncessary one-time workaround from the digest updater GHA
  .github/workflows/notebooks-digest-updater-upstream.yaml
Labels: lgtm, approved

#739 RHOAIENG-7489: Code-Server: Prevent auto updating of the pre-installed extensions
  codeserver/ubi9-python-3.11/run-code-server.sh
  codeserver/ubi9-python-3.9/run-code-server.sh
Labels: lgtm, approved

#741 update test versions for 3.11
  jupyter/datascience/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/minimal/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.11/test/test_notebook.ipynb
Labels: lgtm, approved

#742 [Fix] some pkg versions for the Tensorflow ImageStream manifest
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved

#740 Update codeflare-sdk 0.21.1 version in 2024.1 for ray and certs support
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved, tide/merge-method-squash

#743 [Fix] manifest for TensorFlow image to show proper Numpy package version
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved

#744 NO-JIRA: chore(gha): fix poetry install in GitHub Actions
  .github/workflows/code-quality.yaml
Labels: lgtm, approved

#745 NO-JIRA: chore(gha): pin github runner to ubuntu-22.04 to avoid flaky failures in podman
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved

#746 Updated odh-elyra from 4.0.3 to 4.1.1
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#750 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.22.0
  intel/runtimes/ml/ubi9-python-3.11/Pipfile
  intel/runtimes/ml/ubi9-python-3.11/Pipfile.lock
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.11/Pipfile
  jupyter/intel/ml/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#747 RHOAIENG-14520: fix(vscode): change supervisord files location
  codeserver/ubi9-python-3.11/supervisord/supervisord.conf
  codeserver/ubi9-python-3.9/supervisord/supervisord.conf
  rstudio/c9s-python-3.11/supervisord/supervisord.conf
  rstudio/c9s-python-3.9/supervisord/supervisord.conf
Labels: lgtm, approved

#754 RHOAIENG-14518: feat(codeserver): disable the VSCode workspace trust mechanism and the trust prompt
  codeserver/ubi9-python-3.11/run-code-server.sh
  codeserver/ubi9-python-3.9/run-code-server.sh
Labels: lgtm, approved

#756 RHOAIENG-2003: feat(metadata/codeserver): update VSCode imagestream annotations with installed software
  ci/check-json.sh
  manifests/base/code-server-notebook-imagestream.yaml
Labels: lgtm, approved
