Repository opendatahub-io/notebooks, pull requests merged in 2024-08, with the labels that each got.

#646 Upgrade codeflare-sdk 0.18.0 for py3.9 content
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#656 Update the ROCm versions installed from 6.0 to 6.1 to make it in sync with what we use in Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  rocm/ubi9-python-3.9/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved, tide/merge-method-squash

#663 set the annotation with codeflare-sdk 0.18.0
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm

#652 RHOAIENG-10783: fix(rocm): de-vendor the bundled rocm libraries from pytorch
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/de-vendor-torch.sh
  runtimes/rocm-pytorch/ubi9-python-3.9/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.9/de-vendor-torch.sh
  tests/test_main.py
Labels: lgtm, approved, tide/merge-method-squash

#664 chore(ci): Re-enable Trivy image scan for ROCm Pytorch image
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved

#657 RHOAIENG-9822: chore(Makefile): allow not pushing built images in Makefile and allow skipping building dependent images
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  README.md
  ci/cached-builds/dev_null_container_registry.go
  ci/cached-builds/insecure_localhost_registry.conf
  tests/test_main.py
Labels: lgtm, approved, tide/merge-method-squash

#635 RHOAIENG-10783: fix(Dockerfiles): combine `fix-permissions` RUN with the preceding RUN when possible
  jupyter/datascience/ubi9-python-3.9/Dockerfile
  jupyter/minimal/ubi8-python-3.8/Dockerfile
  jupyter/minimal/ubi9-python-3.9/Dockerfile
  jupyter/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/trustyai/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan

#666 [GHA] Print also images digests after the image build in GitHub repo
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved

#667 RHOAIENG-11087 Fix: Remove install of package in bootstrapper as pre-installed
  runtimes/datascience/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/datascience/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/minimal/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/minimal/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/pytorch/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/tensorflow/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py
Labels: lgtm

#628 Inject rocm runtimes to runtime-images folder
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
Labels: lgtm, approved

#672 RHOAIENG-11216: Add script to automate the creation of a new Python-based image from an existing one
  scripts/README.md
  scripts/new_python_based_image.py
Labels: lgtm, approved, tide/merge-method-squash

#675 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.19.1
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#593 Updated image manifests with AMD images for pytorch and tensorflow
  ci/check-params-env.sh
  manifests/base/commit.env
  manifests/base/commit.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/params.env
  manifests/base/params.yaml
Labels: lgtm, approved

#682 [GHA] Pin kustomize version we use in our test to the particular version
  .github/workflows/code-quality.yaml
Labels: lgtm, approved

#679 Update the codeflare-sdk version in manifest for the relevant images
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml
Labels: lgtm, approved

#683 Update runtime updater workflow to search for the new ROCm runtimes
  .github/workflows/runtimes-digest-updater-upstream.yaml
Labels: lgtm, approved

#685 Use the correct way of ROCm brand in user facing content
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved

#680 RHOAIENG-11090: Create a script to automate multiple library upgrades
  scripts/README.md
  scripts/update_library_version.sh
Labels: lgtm, approved

#688 Update the kfp package version in image manifest to match the reality
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved
