Repository opendatahub-io/notebooks, pull requests merged in 2024-03, with the labels that each got.

#419 Upgrade urllib3 version
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi8-python-3.8/Pipfile
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/minimal/ubi9-python-3.9/Pipfile
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
Labels: lgtm, approved

#443 Upgrade: Update runtime image on main based on the commit id: 016b3d9
  jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Labels: approved

#457 Update README.md
  habana/README.md
Labels: lgtm, approved, needs-ok-to-test

#451 Update notebooks-digest-workflow in favor 2024a release
  .github/workflows/notebooks-digest-updater-upstream.yaml
Labels: lgtm, approved

#458 Remove explicit mention of architecture for oc download
  base/anaconda-python-3.8/Dockerfile
  base/c9s-python-3.9/Dockerfile
  base/ubi8-python-3.8/Dockerfile
  base/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved, ok-to-test

#456 Update Imagestream objects with the N version and drop the old n-2 (n-3) version
  manifests/base/commit.env
  manifests/base/commit.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
Labels: lgtm, approved

#453 Update RStudio Server Notebook
  manifests/base/commit.env
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
  rstudio/c9s-python-3.9/Dockerfile
Labels: lgtm

#428 Intel® PyTorch notebook container
  Makefile
  intel/base/gpu/ubi9-python-3.9/Dockerfile
  intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.9/Pipfile.lock.gpu
  intel/runtimes/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  intel/runtimes/pytorch/ubi9-python-3.9/kustomize/base/pod.yaml
  intel/runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/pytorch/ubi9-python-3.9/oneAPI.repo
  intel/runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
  intel/runtimes/pytorch/ubi9-python-3.9/utils/pip.conf
  intel/runtimes/pytorch/ubi9-python-3.9/utils/requirements-elyra.txt
  jupyter/intel/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.9/Pipfile.cpu
  jupyter/intel/pytorch/ubi9-python-3.9/Pipfile.gpu
  jupyter/intel/pytorch/ubi9-python-3.9/Pipfile.lock.cpu
  jupyter/intel/pytorch/ubi9-python-3.9/Pipfile.lock.gpu
  jupyter/intel/pytorch/ubi9-python-3.9/builder/run
  jupyter/intel/pytorch/ubi9-python-3.9/kernel-gpu.json
  jupyter/intel/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/intel/pytorch/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/intel/pytorch/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/intel/pytorch/ubi9-python-3.9/start-gpu-kernel
  jupyter/intel/pytorch/ubi9-python-3.9/start-notebook.sh
  jupyter/intel/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/intel/pytorch/ubi9-python-3.9/test/test_notebook_cpu.ipynb
  jupyter/intel/pytorch/ubi9-python-3.9/utils/process.sh
Labels: lgtm, approved, ok-to-test

#455 Upgrade runtime images and test jupyter notebooks
  jupyter/datascience/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/tensorflow/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/tensorflow/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
  runtimes/datascience/ubi8-python-3.8/Pipfile
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm

#449 2024a version Package upgrades across all images.
  Makefile
  base/c9s-python-3.9/Pipfile
  base/c9s-python-3.9/Pipfile.lock
  base/ubi8-python-3.8/Pipfile
  base/ubi8-python-3.8/Pipfile.lock
  base/ubi9-python-3.9/Pipfile
  base/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi8-python-3.8/Pipfile
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Labels: approved

#454 Update CUDA layer to 12.1
  cuda/c9s-python-3.9/Dockerfile
  cuda/c9s-python-3.9/cuda.repo-arm64
  cuda/ubi8-python-3.8/Dockerfile
  cuda/ubi8-python-3.8/cuda.repo-arm64
  cuda/ubi8-python-3.8/cuda.repo-ppc64le
  cuda/ubi9-python-3.9/Dockerfile
  cuda/ubi9-python-3.9/cuda.repo-arm64
Labels: lgtm, approved

#422 Intel® TensorFlow notebook container
  Makefile
  intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  intel/runtimes/tensorflow/ubi9-python-3.9/kustomize/base/pod.yaml
  intel/runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/tensorflow/ubi9-python-3.9/oneAPI.repo
  intel/runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  intel/runtimes/tensorflow/ubi9-python-3.9/utils/pip.conf
  intel/runtimes/tensorflow/ubi9-python-3.9/utils/requirements-elyra.txt
  jupyter/intel/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.9/Pipfile.cpu
  jupyter/intel/tensorflow/ubi9-python-3.9/Pipfile.gpu
  jupyter/intel/tensorflow/ubi9-python-3.9/Pipfile.lock.cpu
  jupyter/intel/tensorflow/ubi9-python-3.9/Pipfile.lock.gpu
  jupyter/intel/tensorflow/ubi9-python-3.9/builder/run
  jupyter/intel/tensorflow/ubi9-python-3.9/kernel-gpu.json
  jupyter/intel/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/intel/tensorflow/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/intel/tensorflow/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/intel/tensorflow/ubi9-python-3.9/start-gpu-kernel
  jupyter/intel/tensorflow/ubi9-python-3.9/start-notebook.sh
  jupyter/intel/tensorflow/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/intel/tensorflow/ubi9-python-3.9/test/test_notebook_cpu.ipynb
  jupyter/intel/tensorflow/ubi9-python-3.9/utils/process.sh
Labels: lgtm, approved, ok-to-test

#434 Intel® optimized ML notebook container
  Makefile
  intel/runtimes/ml/ubi9-python-3.9/.patch_sklearn.py
  intel/runtimes/ml/ubi9-python-3.9/Dockerfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/kustomize/base/kustomization.yaml
  intel/runtimes/ml/ubi9-python-3.9/kustomize/base/pod.yaml
  intel/runtimes/ml/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
  intel/runtimes/ml/ubi9-python-3.9/utils/bootstrapper.py
  intel/runtimes/ml/ubi9-python-3.9/utils/pip.conf
  intel/runtimes/ml/ubi9-python-3.9/utils/requirements-elyra.txt
  jupyter/intel/ml/ubi9-python-3.9/Dockerfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/intel/ml/ubi9-python-3.9/builder/run
  jupyter/intel/ml/ubi9-python-3.9/kustomize/base/kustomization.yaml
  jupyter/intel/ml/ubi9-python-3.9/kustomize/base/service.yaml
  jupyter/intel/ml/ubi9-python-3.9/kustomize/base/statefulset.yaml
  jupyter/intel/ml/ubi9-python-3.9/start-notebook.sh
  jupyter/intel/ml/ubi9-python-3.9/test/test_notebook.ipynb
  jupyter/intel/ml/ubi9-python-3.9/utils/process.sh
Labels: lgtm, ok-to-test

#472 Update TrustyAi package from 0.3 to 0.6 due to CVE-202347248
  jupyter/trustyai/ubi8-python-3.8/Pipfile
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#463 Update GH actions to use Node20
  .github/workflows/auto-add-issue-to-project.yml
  .github/workflows/notebooks-digest-updater-upstream.yaml
  .github/workflows/params-env.yaml
  .github/workflows/piplock-renewal-2023a.yml
  .github/workflows/piplock-renewal-2023b.yml
  .github/workflows/pr-merge-image-delete.yml
  .github/workflows/sec-scan.yml
Labels: lgtm

#462 [CI] fix the expected metadata of the images
  ci/check-params-env.sh
  ci/hadolint-config.yaml
  intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
  intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile
Labels: lgtm

#473 Update Makefile: Add OS dependant generation of date, selection of proper cmd to locate container engine and automatically select available container engine
  Makefile
  intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
  intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/intel/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/intel/tensorflow/ubi9-python-3.9/Dockerfile
Labels: lgtm, approved, ok-to-test

#380 Add Habana 1.13 notebook
  Makefile
  habana/1.13.0/ubi8-python-3.8/Dockerfile
  habana/1.13.0/ubi8-python-3.8/Pipfile
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  habana/1.13.0/ubi8-python-3.8/README.md
  habana/1.13.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
  habana/1.13.0/ubi8-python-3.8/kustomize/base/service.yaml
  habana/1.13.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
Labels: lgtm, approved

#476 updating Anaconda dependencies
  base/anaconda-python-3.8/environment.yml
  jupyter/datascience/anaconda-python-3.8/Dockerfile
  jupyter/datascience/anaconda-python-3.8/environment.in
  jupyter/datascience/anaconda-python-3.8/environment.yml
Labels: lgtm, approved, ok-to-test

#478 Remove kfp_tekton from the testing notebooks
  jupyter/datascience/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved

#480 Include the Intel based ML, PyTorch, TensorFlow Images to Workbenches…
  manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-pytorch-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-tensorflow-notebook-imagestream.yaml
  manifests/overlays/additional/kustomization.yaml
Labels: lgtm

#482 Remove kfp LocalClient lib from datascience notebook testing since it…
  jupyter/datascience/ubi8-python-3.8/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb
Labels: lgtm, approved
