Repository opendatahub-io/notebooks, pull requests merged in 2025-07, with the labels that each got.

#1228 [2024b] RHOAIENG-18535: chore(deps): bump mysql-connector-python from 9.0.0 to 9.1.0 in Pipfiles
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: tide/merge-method-squash, trivy-scan, size/xxl

#1229 chore: add linux/amd64 default build_arch on the Makefile build command
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/create-release.yaml
  .github/workflows/notebooks-release.yaml
  Makefile
Labels: lgtm, approved, size/s

#1151 RHOAIENG-26921: Create Jupyter Tensorflow Python 3.12 Image
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.12/Pipfile
  jupyter/tensorflow/ubi9-python-3.12/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.12/kustomize/base/kustomization.yaml
  jupyter/tensorflow/ubi9-python-3.12/kustomize/base/service.yaml
  jupyter/tensorflow/ubi9-python-3.12/kustomize/base/statefulset.yaml
  jupyter/tensorflow/ubi9-python-3.12/requirements.txt
  jupyter/tensorflow/ubi9-python-3.12/test/test_notebook.ipynb
Labels: lgtm, approved, size/xxl

#1247 RHOAIENG-28514, RHOAIENG-28513: incorporate python-3.12 workbench images into project's Makefile in opendatahub-io/notebooks
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/build-notebooks-pr-rhel.yaml
  .github/workflows/build-notebooks-pr.yaml
  .github/workflows/build-notebooks-push.yaml
  .github/workflows/piplock-renewal.yaml
  Makefile
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/gha_pr_changed_files.py
  ci/cached-builds/has_tests.py
  ci/cached-builds/makefile_helper.py
Labels: tide/merge-method-squash, size/l

#1257 NO-JIRA fix(gha): prevent misleading compsize error in CI
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, tide/merge-method-squash, size/xs

#1327 NO-JIRA: configure kubelet to disable image garbage collection in kubeadm CI config
  ci/cached-builds/kubeadm.yaml
Labels: tide/merge-method-squash, trivy-scan, size/s

#1328 NO-JIRA: update Trivy version in CI and improve comments
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: tide/merge-method-squash, trivy-scan, size/xs

#1329 Revert "RHOAIENG-16076: tests(gha): pre-pull trivy vulnerabilities db to prevent failures to download later (#777)"
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved, tide/merge-method-squash, trivy-scan, size/m

#1325 RHOAIENG-28509: release new version of odh-elyra to get fix for RHOAIENG-25809
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.12/Pipfile
  jupyter/datascience/ubi9-python-3.12/Pipfile.lock
  jupyter/datascience/ubi9-python-3.12/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.12/Pipfile
  jupyter/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.12/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.12/Pipfile
  jupyter/tensorflow/ubi9-python-3.12/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.12/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.12/Pipfile
  jupyter/trustyai/ubi9-python-3.12/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.12/requirements.txt
  runtimes/datascience/ubi9-python-3.12/Pipfile.lock
  runtimes/datascience/ubi9-python-3.12/requirements.txt
  runtimes/minimal/ubi9-python-3.12/Pipfile.lock
  runtimes/minimal/ubi9-python-3.12/requirements.txt
  runtimes/pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.12/requirements.txt
  runtimes/tensorflow/ubi9-python-3.12/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.12/requirements.txt
Labels: size/l

#1357 RHOAIENG-28774: update Python 3.12 codeserver image Dockerfile for using TARGETARCH
  codeserver/ubi9-python-3.12/Dockerfile.cpu
Labels: lgtm, ok-to-test, tide/merge-method-squash, trivy-scan, size/xs

#1374 ISSUE #1370: fix(gha): yamllint in insta-merge workflow
  .github/workflows/insta-merge.yaml
Labels: size/xs

#1376 ISSUE #1292: fix typos in codeserver documentation and comments
  codeserver/ubi9-python-3.11/Dockerfile.cpu
  codeserver/ubi9-python-3.11/run-nginx.sh
  codeserver/ubi9-python-3.12/Dockerfile.cpu
  codeserver/ubi9-python-3.12/run-nginx.sh
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/c9s-python-3.11/run-nginx.sh
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/run-nginx.sh
Labels: lgtm, size/s

#1118 RHOAIENG-25226: update params-latest.env references to new konflux repositories
  manifests/base/params-latest.env
Labels: do-not-merge/hold, size/m

#1379 RHOAIENG-28512: add py312 .tekton push pipelines
  .tekton/odh-pipeline-runtime-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py312-ubi9-push.yaml
Labels: tide/merge-method-squash, size/xxl

#1385 refactor(gha, makefile): improve piplock renewal process log printout
  .github/workflows/piplock-renewal.yaml
  Makefile
Labels: size/xs

#1387 Ignore yamllint in konflux insta-merge.yaml file
  .github/workflows/code-quality.yaml
Labels: size/xs

#1372 Add some missing images on the py312 all-images target
  .github/workflows/insta-merge.yaml
  Makefile
Labels: lgtm, approved, size/s

#1397 Enhance Pipfile.lock GitHub Action: Multi-version Matrix Support
  .github/workflows/piplock-renewal.yaml
  Makefile
Labels: tide/merge-method-squash, size/m

#1399 NO-JIRA: fix(manifests): set full repo path in workbench image references in `params-latest.env`
  manifests/base/params-latest.env
Labels: lgtm, size/m

#1386 Add libxcrypt-compat to provide libcrypt.so.1
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.cuda
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.rocm
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
Labels: size/s

#1403 Set the new ordering of the imagestreams on UI
  ci/package_versions_selftestdata.py
  manifests/base/README.md
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
  manifests/base/runtime-datascience-imagestream.yaml
  manifests/base/runtime-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-tensorflow-imagestream.yaml
  manifests/base/runtime-tensorflow-imagestream.yaml
  manifests/overlays/additional/code-server-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-datascience-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-minimal-gpu-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-minimal-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-pytorch-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-rocm-minimal-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-rocm-pytorch-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-tensorflow-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-trustyai-notebook-imagestream-beta.yaml
  manifests/overlays/additional/runtime-datascience-imagestream-beta.yaml
  manifests/overlays/additional/runtime-minimal-imagestream-beta.yaml
  manifests/overlays/additional/runtime-pytorch-imagestream-beta.yaml
  manifests/overlays/additional/runtime-rocm-pytorch-imagestream-beta.yaml
  manifests/overlays/additional/runtime-tensorflow-imagestream-beta.yaml
Labels: lgtm, approved, size/l

#1404 Set py3.12 imagestream name based on naming convention
  manifests/base/README.md
  manifests/overlays/additional/codeserver-datascience-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-datascience-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-minimal-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-minimal-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-minimal-rocm-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-pytorch-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-pytorch-rocm-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-tensorflow-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-trustyai-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/kustomization.yaml
  manifests/overlays/additional/runtime-datascience-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-minimal-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-pytorch-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-pytorch-rocm-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-tensorflow-cuda-py312-ubi9-imagestream.yaml
Labels: approved, size/l

#1410 [RHOAIENG-29979] Update params-latest to have a mix of konflux and ocp-ci buildsand update commit SHAs for image digests changes
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: lgtm, approved, size/l

#1408 Issue #385: decrease Python 3.12 CUDA images size by installing less
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.cuda
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
Labels: lgtm, tide/merge-method-squash, size/l

#1413 Fix additional-tags on the pipeline configs
  .tekton/odh-pipeline-runtime-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cpu-py311-c9s-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cuda-py311-c9s-push.yaml
Labels: size/m

#1409 [RHOAIENG-26264] commit*.env references updates automatically at 11:00 UTC using cron job
  .github/workflows/update-commit-latest-env.yaml
Labels: lgtm, approved, size/xs

#1415 RHOAIENG-28514, RHOAIENG-28513: ci(gha): remove Python 3.12 exclusion for .ipynb testing
  ci/cached-builds/has_tests.py
Labels: size/xs

#1419 RHOAIENG-18535, RHOAIENG-11812, RHOAIENG-18601, RHOAIENG-18613: bump …
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, size/s

#1420 [RHOAIENG-26066] bump TrustyAI image transformers in manifests too
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: size/xs

#1396 Enable arm64 for Tensorflow CUDA images
  ci/cached-builds/gen_gha_matrix_jobs.py
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.12/Pipfile
  jupyter/tensorflow/ubi9-python-3.12/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.12/requirements.txt
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  runtimes/tensorflow/ubi9-python-3.12/Pipfile
  runtimes/tensorflow/ubi9-python-3.12/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.12/requirements.txt
Labels: lgtm, approved, size/l

#1433 Use revision tag on output image
  .tekton/odh-pipeline-runtime-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cpu-py311-c9s-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cuda-py311-c9s-push.yaml
Labels: size/m

#1462 RHOAIENG-30247: chore(deps): bump PyTorch packages across all Pipfiles (torch 2.6.0, torchvision 0.21.0, tensorboard 2.17.1)
  codeserver/ubi9-python-3.11/Pipfile
  codeserver/ubi9-python-3.11/Pipfile.lock
  codeserver/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/minimal/ubi9-python-3.11/Pipfile.lock
  runtimes/minimal/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, tide/merge-method-squash, size/xxl

#1464 [2024b] RHOAIENG-30247: chore(deps): bump transformers to 4.52.1 in trustyai Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
Labels: lgtm, tide/merge-method-squash, size/l

#1489 [2024b] RHOAIENG-30247 chore(deps): Bump codeflare-sdk version from `0.26.0` to `0.28.0`
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, approved, size/xxl

#1497 RHOAIENG-30439: tekton: add PipelineRun definition for minimal CPU Python 3.12 UBI9 runtime
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-pull-request.yaml
Labels: lgtm, tide/merge-method-squash, size/xl

#1500 RHOAIENG-30439: tekton: fix `on-cel-expression` for minimal CPU Python 3.12 UBI9 runtime
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-pull-request.yaml
Labels: size/xs

#1501 RHOAIENG-30439: tekton: factor out the common `multiarch-pull-request-pipeline` into its own file
  .tekton/multiarch-pull-request-pipeline.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-ubi9-pull-request.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-pull-request.yaml
Labels: tide/merge-method-squash, size/xxl

#1503 [2024b] RHOAIENG-28774: update the 2024b GitHub Action so that it does not end up pulling the wrong cache
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved, tide/merge-method-squash, size/xs

#1507 Update rstudio references to the new registries
  manifests/base/params-latest.env
Labels: approved, size/xs

#1545 RHOAIENG-30927, RHOAIENG-10057: add `dnf upgrade` to rstudio images to mitigate fixable vulnerabilities (#1488)
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
Labels: lgtm, approved, size/s

#1569 Remove double references of the runtime-pytorch-rocm-py312-ubi9-n on params-latest and commits-latest files
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: lgtm, approved, size/xs
