Repository opendatahub-io/notebooks, pull requests merged in 2025-06, with the labels that each got.

#1137 RHOAIENG-24438: Create Jupyter Data Science Python 3.12 Image
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.12/Pipfile
  jupyter/datascience/ubi9-python-3.12/Pipfile.lock
  jupyter/datascience/ubi9-python-3.12/kustomize/base/kustomization.yaml
  jupyter/datascience/ubi9-python-3.12/kustomize/base/service.yaml
  jupyter/datascience/ubi9-python-3.12/kustomize/base/statefulset.yaml
  jupyter/datascience/ubi9-python-3.12/mssql-2022.repo-x86_64
  jupyter/datascience/ubi9-python-3.12/requirements.txt
  jupyter/datascience/ubi9-python-3.12/setup-elyra.sh
  jupyter/datascience/ubi9-python-3.12/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.12/utils/component_runtime.json
  jupyter/datascience/ubi9-python-3.12/utils/jupyter_elyra_config.py
  jupyter/datascience/ubi9-python-3.12/utils/kfp_authentication.patch
  jupyter/datascience/ubi9-python-3.12/utils/pipeline-flow.svg
  jupyter/datascience/ubi9-python-3.12/utils/pipeline_app.patch
  jupyter/datascience/ubi9-python-3.12/utils/pipeline_definition.patch
  jupyter/datascience/ubi9-python-3.12/utils/processor_kfp.patch
Labels: lgtm, approved, size/xxl

#1030 RHOAIENG-16568: [Bug] Unable to download notebook as a PDF from JupyterLab Workbenches
  .gitignore
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
  jupyter/utils/install_pdf_deps.sh
  jupyter/utils/jupyter_server_config.py
  scripts/check-payload/config.toml
  tests/containers/workbenches/jupyterlab/jupyterlab_test.py
Labels: lgtm, approved, tide/merge-method-squash, size/l

#1138 RHOAIENG-24471: Create Jupyter Pytorch Python 3.12 Image
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/Pipfile
  jupyter/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.12/dependencies.custom.in
  jupyter/pytorch/ubi9-python-3.12/kustomize/base/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/base/service.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/base/statefulset.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/components/accelerator/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/components/accelerator/pod-patch.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/overlays/accelerator/cuda/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/overlays/accelerator/cuda/pod-patch.yaml
  jupyter/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/pytorch/ubi9-python-3.12/targets.custom.in
  jupyter/pytorch/ubi9-python-3.12/test/test_notebook.ipynb
Labels: lgtm, approved, size/xxl

#1155 RHOAIENG-717: fix `image-tag-outdated` annotation description in `workbench-imagestreams.md`
  docs/workbench-imagestreams.md
Labels: lgtm, tide/merge-method-squash, size/xs

#1154 RHOAIENG-26702: Update codeflare-sdk versions and shas for v0.29.0
  codeserver/ubi9-python-3.11/Pipfile.lock
  codeserver/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: tide/merge-method-squash, size/xxl

#1156 RHOAIENG-26264: fix automatic updates of commit-latest.env references
  .github/workflows/update-commit-latest-env.yaml
  scripts/update-commit-latest-env.py
Labels: lgtm, tide/merge-method-squash, size/l

#1132 RHOAISTRAT-169: add conditional package install in minimal Dockerfile.cpu for s390x
  runtimes/minimal/ubi9-python-3.11/Dockerfile.cpu
Labels: lgtm, approved, ok-to-test, size/xs

#1165 RHOAIENG-26264: throttle concurrent skopeo invocations to at most 22 concurrent skopeo instances running
  scripts/update-commit-latest-env.py
Labels: lgtm, tide/merge-method-squash, size/m

#1166 ref(Dockerfiles): reduce duplication in `runtimes/minimal/ubi9-python-3.11/Dockerfile.cpu` package installation
  runtimes/minimal/ubi9-python-3.11/Dockerfile.cpu
Labels: size/xs

#1176 Change RHOAI version from 2.21 to 2.22
  manifests/base/cuda-rstudio-buildconfig.yaml
  manifests/base/rstudio-buildconfig.yaml
Labels: lgtm, size/xs

#1171 RHOAIENG-26843, RHOAIENG-26066: tests: add scikit-learn smoke test
  tests/containers/conftest.py
  tests/containers/workbenches/jupyterlab/jupyterlab_datascience_test.py
Labels: tide/merge-method-squash, size/m

#1187 RHOAIENG-26843: add trustyai compatibility smoke test for JupyterLab images with scikit-learn
  tests/containers/conftest.py
  tests/containers/workbenches/jupyterlab/jupyterlab_trustyai_test.py
Labels: lgtm, size/l

#1210 RHOAIENG-18535, RHOAIENG-11812, RHOAIENG-18601, RHOAIENG-18613: bump `mysql-connector-python` to 9.3.0 in all Python 3.11 Pipfiles
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: tide/merge-method-squash, size/xxl

#1230 RHOAIENG-28511: merge the python-3.12 branch to opendatahub-io/notebooks#main
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.12/Pipfile
  jupyter/datascience/ubi9-python-3.12/Pipfile.lock
  jupyter/datascience/ubi9-python-3.12/kustomize/base/kustomization.yaml
  jupyter/datascience/ubi9-python-3.12/kustomize/base/service.yaml
  jupyter/datascience/ubi9-python-3.12/kustomize/base/statefulset.yaml
  jupyter/datascience/ubi9-python-3.12/mssql-2022.repo-x86_64
  jupyter/datascience/ubi9-python-3.12/requirements.txt
  jupyter/datascience/ubi9-python-3.12/setup-elyra.sh
  jupyter/datascience/ubi9-python-3.12/test/test_notebook.ipynb
  jupyter/datascience/ubi9-python-3.12/utils/component_runtime.json
  jupyter/datascience/ubi9-python-3.12/utils/jupyter_elyra_config.py
  jupyter/datascience/ubi9-python-3.12/utils/kfp_authentication.patch
  jupyter/datascience/ubi9-python-3.12/utils/pipeline-flow.svg
  jupyter/datascience/ubi9-python-3.12/utils/pipeline_app.patch
  jupyter/datascience/ubi9-python-3.12/utils/pipeline_definition.patch
  jupyter/datascience/ubi9-python-3.12/utils/processor_kfp.patch
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.rocm
  jupyter/minimal/ubi9-python-3.12/Pipfile
  jupyter/minimal/ubi9-python-3.12/Pipfile.lock
  jupyter/minimal/ubi9-python-3.12/kustomize/base/kustomization.yaml
  jupyter/minimal/ubi9-python-3.12/kustomize/base/service.yaml
  jupyter/minimal/ubi9-python-3.12/kustomize/base/statefulset.yaml
  jupyter/minimal/ubi9-python-3.12/requirements.txt
  jupyter/minimal/ubi9-python-3.12/start-notebook.sh
  jupyter/minimal/ubi9-python-3.12/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/Pipfile
  jupyter/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.12/dependencies.custom.in
  jupyter/pytorch/ubi9-python-3.12/kustomize/base/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/base/service.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/base/statefulset.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/components/accelerator/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/components/accelerator/pod-patch.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/overlays/accelerator/cuda/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.12/kustomize/overlays/accelerator/cuda/pod-patch.yaml
  jupyter/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/pytorch/ubi9-python-3.12/targets.custom.in
  jupyter/pytorch/ubi9-python-3.12/test/test_notebook.ipynb
Labels: lgtm, approved, size/xxl
