Repository opendatahub-io/notebooks, pull requests merged in 2025-05, with the labels that each got.

#1032 NO-JIRA: fix(pydantic_schemas): new podman version changed output of `podman info`
  tests/containers/pydantic_schemas/podman_info.py
Labels: lgtm, approved, size/xs

#1038 include vllm package with llmcompressor
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Pipfile
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/requirements.txt
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Pipfile
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/requirements.txt
Labels: size/xxl

#1029 RHOAIENG-24684: fix(jupyter/utils/addon) fix vertical centering of the PatternFly spinner
  jupyter/utils/addons/partial-head.html
Labels: lgtm, size/xs

#1033 RHOAIENG-23584: test(run-rstudio.sh): fix tests to more correctly check for exposed env variables
  tests/containers/workbenches/rstudio/rstudio_test.py
Labels: size/m

#1028 NO-JIRA: docs: update outdated internal docs after the buildchain refactoring
  jupyter/utils/README.md
  jupyter/utils/addons/apply.sh
Labels: lgtm, approved, size/xs

#1024 RHOAIENG-24181: chore(jupyter/utils/addons): tree-shake the PatternFly CSS used to add spinner to JupyterLab-based workbenches
  .github/workflows/code-quality.yaml
  jupyter/utils/addons/.dockerignore
  jupyter/utils/addons/.gitignore
  jupyter/utils/addons/README.md
  jupyter/utils/addons/apply.sh
  jupyter/utils/addons/cleanup-webpack-plugin.ts
  jupyter/utils/addons/dist/index.html
  jupyter/utils/addons/dist/pf.css
  jupyter/utils/addons/package.json5
  jupyter/utils/addons/pnpm-lock.yaml
  jupyter/utils/addons/src/index.ejs
  jupyter/utils/addons/test-build.sh
  jupyter/utils/addons/tsconfig.json
  jupyter/utils/addons/webpack.config.ts
Labels: size/xxl

#894 NO-JIRA: docs(tests/): add interactive PyTest tutorial
  tests/pytest_tutorial/test_01_intro.py
Labels: tide/merge-method-squash, size/l

#1039 NO-JIRA: Fix linter warnings in test_01_intro.py
  tests/pytest_tutorial/test_01_intro.py
Labels: lgtm, approved, size/xs

#1043 NO-JIRA: tests(gha/k8s): install contrack and address kubernetes version compatibility issues
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, size/s

#1046 NO-JIRA: tests(browser/): update dependencies in `pnpm-lock.yaml`
  .github/workflows/build-notebooks-TEMPLATE.yaml
  tests/browser/package.json
  tests/browser/pnpm-lock.yaml
  tests/browser/tests/codeserver.spec.ts
Labels: approved, size/l

#1047 NO-JIRA: tests(gha/k8s): `kubeadm config migrate --old-config kubeadm.yaml.old --new-config kubeadm.yaml`
  ci/cached-builds/kubeadm.yaml
Labels: size/m

#1068 NO-JIRA: tests(gha/k8s): remove setting the `node-role.kubernetes.io/control-plane` taint
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/kubeadm.yaml
Labels: lgtm, size/xs

#1072 NO-JIRA: tests(browser/): add Cypress section to the README.md
  tests/browser/README.md
Labels: size/l

#1080 NO-JIRA: tests(gha): add `check-payload` integration and dependency management
  .github/workflows/build-notebooks-TEMPLATE.yaml
  scripts/check-payload/config.toml
  scripts/check-payload/go.mod
  scripts/check-payload/go.sum
  scripts/check-payload/tools.go
Labels: tide/merge-method-squash, size/xxl

#1077 NO-JIRA: tests(containers): use Skopeo for remote image inspection in tests
  tests/containers/conftest.py
  tests/containers/skopeo_utils.py
  tests/containers/utils.py
  tests/containers/workbenches/jupyterlab/jupyterlab_test.py
  tests/containers/workbenches/rstudio/rstudio_test.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/l

#1084 NO-JIRA: tests(gha): fix `check-payload` to work with PRs and without `podman login` for root user
  .github/workflows/build-notebooks-TEMPLATE.yaml
  scripts/check-payload/config.toml
Labels: lgtm, size/s

#1044 RHOAIENG-23604, RHOAIENG-16094: update `ODH-Elyra` to `4.2.1`
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
Labels: lgtm, approved, size/m

#1070 RHOAIENG-25226: Standardize the image name with image convention
  .github/workflows/params-env.yaml
  ci/check-params-env.sh
  ci/check-runtime-images.sh
  ci/check-software-versions.py
  ci/package_versions_selftestdata.py
  ci/security-scan/quay_security_analysis.py
  ci/security-scan/weekly_commit_ids.env
  ci/sha-digest-updater.sh
  docs/workbenches-naming.md
  manifests/base/README.md
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/commit-latest.env
  manifests/base/commit.env
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params-latest.env
  manifests/base/params.env
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
  manifests/base/runtime-datascience-imagestream.yaml
  manifests/base/runtime-minimal-imagestream.yaml
  manifests/base/runtime-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-tensorflow-imagestream.yaml
  manifests/base/runtime-tensorflow-imagestream.yaml
Labels: lgtm, approved, tide/merge-method-squash, size/xxl

#1087 Build mongocli instead of downloading it pre-built
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.11/mongodb-org-6.0.repo-x86_64
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
  scripts/check-payload/config.toml
Labels: lgtm, approved, size/l

#1119 [docs] Update the reference to the upstream -> downstream sync GHA
  docs/developer-guide.md
Labels: lgtm, approved, size/xs

#1121 NO-JIRA: tests(gha): fix podman.sock cleanup in system reset for build workflow
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/podman.service
  ci/cached-builds/podman.socket
Labels: lgtm, size/s

#1124 RHOAIENG-25226: don't build images if we are only changing manifests
  .github/workflows/build-notebooks-pr-rhel.yaml
  .github/workflows/build-notebooks-pr.yaml
  .github/workflows/build-notebooks-push.yaml
Labels: lgtm, approved, size/s

#1128 [NO-JIRA] chore: exclude the .tekton dir from yamllint check
  .github/workflows/code-quality.yaml
Labels: lgtm, approved, size/xs

#1134 NO-JIRA: chore(check-params-env GHA): Prepare for the konflux build images
  ci/check-params-env.sh
Labels: lgtm, size/m

#1135 NO-JIRA: chore(check-params-env GHA): fix the variable parsing
  ci/check-params-env.sh
Labels: lgtm, size/xs
