Repository opendatahub-io/notebooks, pull requests merged in 2025-04, with the labels that each got.

#995 [GHA] Enhance the checks for the kustomization.yaml files
  .github/workflows/code-quality.yaml
  ci/kustomize.sh
Labels: lgtm, approved, size/m

#1001 NO-ISSUE: chore(GHA): add skopeo retry in case it fails first time
  ci/check-params-env.sh
  ci/check-runtime-images.sh
Labels: lgtm, approved, size/s

#917 RHOAIENG-17006: chore(pyproject.toml): migrate test dependencies from poetry to uv
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/code-quality.yaml
  .github/workflows/docs.yaml
  .python-version
  README.md
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  ci/cached-builds/konflux_generate_component_definitions.py
  poetry.lock
  pyproject.toml
  uv.lock
Labels: approved, size/xxl

#1005 RHOAIENG-22425: chore(konflux): implement nudging to keep a (separate) manifests repo up-to-date
  .tekton/codeserver-ubi9-python-3-11-push.yaml
  .tekton/cuda-jupyter-minimal-ubi9-python-3-11-push.yaml
  .tekton/cuda-jupyter-pytorch-ubi9-python-3-11-push.yaml
  .tekton/cuda-jupyter-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/cuda-rstudio-c9s-python-3-11-push.yaml
  .tekton/cuda-rstudio-rhel9-python-3-11-push.yaml
  .tekton/jupyter-datascience-ubi9-python-3-11-push.yaml
  .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
  .tekton/jupyter-trustyai-ubi9-python-3-11-push.yaml
  .tekton/rocm-jupyter-minimal-ubi9-python-3-11-push.yaml
  .tekton/rocm-jupyter-pytorch-ubi9-python-3-11-push.yaml
  .tekton/rocm-jupyter-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/rocm-runtime-pytorch-ubi9-python-3-11-push.yaml
  .tekton/rocm-runtime-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/rstudio-c9s-python-3-11-push.yaml
  .tekton/rstudio-rhel9-python-3-11-push.yaml
  .tekton/runtime-cuda-pytorch-ubi9-python-3-11-push.yaml
  .tekton/runtime-cuda-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/runtime-datascience-ubi9-python-3-11-push.yaml
  .tekton/runtime-minimal-ubi9-python-3-11-push.yaml
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  ci/cached-builds/konflux_generate_component_definitions.py
Labels: lgtm, approved, size/s

#1002 [Kubeflow-Training] Update notebook's pipfile to sync with Kubeflow-Training SDK release 1.9.1
  codeserver/ubi9-python-3.11/Pipfile
  codeserver/ubi9-python-3.11/Pipfile.lock
  codeserver/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/minimal/ubi9-python-3.11/Pipfile.lock
  runtimes/minimal/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, size/xxl

#1007 NO-JIRA: chore(ci): add pre-commit checks for Python code
  .github/workflows/code-quality.yaml
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: lgtm, approved, size/l

#1008 NO-JIRA: chore(pyright): fix types in the checked code so that Pyright passes
  .pre-commit-config.yaml
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  ci/package_versions.py
  tests/containers/conftest.py
  tests/containers/kubernetes_utils.py
  tests/containers/socket_proxy.py
Labels: approved, tide/merge-method-squash, size/m

#1000 NO-ISSUE: chore(GHA): update expected image size for 2025.1 version
  ci/check-params-env.sh
  ci/check-runtime-images.sh
Labels: lgtm, approved, size/m

#1010 Upgrade llmcompressor to version 0.5
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Pipfile
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/requirements.txt
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/runtime-images/llmcompressor-pytorch-ubi9-py311.json
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Pipfile
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/requirements.txt
Labels: lgtm, size/xxl

#1009 NO-JIRA: chore(ruff): fix indentation and linting in the checked code so that ruff passes
  .editorconfig
  .pre-commit-config.yaml
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/gha_pr_changed_files.py
  ci/cached-builds/has_tests.py
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  ci/cached-builds/konflux_generate_component_definitions.py
  ci/cached-builds/make_test.py
  ci/check-software-versions.py
  ci/package_versions.py
  ci/security-scan/quay_security_analysis.py
  pyproject.toml
  tests/__init__.py
  tests/containers/base_image_test.py
  tests/containers/cancellation_token.py
  tests/containers/conftest.py
  tests/containers/docker_utils.py
  tests/containers/kubernetes_utils.py
  tests/containers/podman_machine_utils.py
  tests/containers/pydantic_schemas/__init__.py
  tests/containers/pydantic_schemas/podman_info.py
  tests/containers/pydantic_schemas/podman_machine_inspect.py
  tests/containers/socket_proxy.py
  tests/containers/utils.py
  tests/containers/workbenches/jupyterlab/jupyterlab_test.py
  tests/containers/workbenches/rstudio/rstudio_test.py
  tests/containers/workbenches/workbench_image_test.py
  tests/test_main.py
Labels: approved, tide/merge-method-squash, size/xxl

#943 Remove .json files runtimes from DS notebook & removed the COPY instruction of them on the Dockerfile
  .tekton/cuda-jupyter-pytorch-ubi9-python-3-11-pull-request.yaml
  .tekton/cuda-jupyter-tensorflow-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-datascience-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-trustyai-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-jupyter-pytorch-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-jupyter-tensorflow-ubi9-python-3-11-pull-request.yaml
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.11/runtime-images/datascience-ubi9-py311.json
  jupyter/datascience/ubi9-python-3.11/runtime-images/pytorch-ubi9-py311.json
  jupyter/datascience/ubi9-python-3.11/runtime-images/rocm-pytorch-ubi9-py311.json
  jupyter/datascience/ubi9-python-3.11/runtime-images/rocm-tensorflow-ubi9-py311.json
  jupyter/datascience/ubi9-python-3.11/runtime-images/tensorflow-ubi9-py311.json
  jupyter/datascience/ubi9-python-3.11/runtime-images/ubi9-py311.json
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
  manifests/base/kustomization.yaml
Labels: lgtm, approved, tide/merge-method-squash, size/l

#1013 RHOAIENG-20241: fix the CI check for the runtime image definition
  .github/workflows/params-env.yaml
  ci/check-runtime-images.sh
Labels: lgtm, approved, size/m

#1012 NO-JIRA: add a 'release' label to our images
  .tekton/codeserver-ubi9-python-3-11-pull-request.yaml
  .tekton/codeserver-ubi9-python-3-11-push.yaml
  .tekton/cuda-jupyter-minimal-ubi9-python-3-11-pull-request.yaml
  .tekton/cuda-jupyter-minimal-ubi9-python-3-11-push.yaml
  .tekton/cuda-jupyter-pytorch-ubi9-python-3-11-pull-request.yaml
  .tekton/cuda-jupyter-pytorch-ubi9-python-3-11-push.yaml
  .tekton/cuda-jupyter-tensorflow-ubi9-python-3-11-pull-request.yaml
  .tekton/cuda-jupyter-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/cuda-rstudio-c9s-python-3-11-pull-request.yaml
  .tekton/cuda-rstudio-c9s-python-3-11-push.yaml
  .tekton/cuda-rstudio-rhel9-python-3-11-pull-request.yaml
  .tekton/cuda-rstudio-rhel9-python-3-11-push.yaml
  .tekton/jupyter-datascience-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-datascience-ubi9-python-3-11-push.yaml
  .tekton/jupyter-minimal-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
  .tekton/jupyter-trustyai-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-trustyai-ubi9-python-3-11-push.yaml
  .tekton/rocm-jupyter-minimal-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-jupyter-minimal-ubi9-python-3-11-push.yaml
  .tekton/rocm-jupyter-pytorch-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-jupyter-pytorch-ubi9-python-3-11-push.yaml
  .tekton/rocm-jupyter-tensorflow-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-jupyter-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/rocm-runtime-pytorch-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-runtime-pytorch-ubi9-python-3-11-push.yaml
  .tekton/rocm-runtime-tensorflow-ubi9-python-3-11-pull-request.yaml
  .tekton/rocm-runtime-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/rstudio-c9s-python-3-11-pull-request.yaml
  .tekton/rstudio-c9s-python-3-11-push.yaml
  .tekton/rstudio-rhel9-python-3-11-pull-request.yaml
  .tekton/rstudio-rhel9-python-3-11-push.yaml
  .tekton/runtime-cuda-pytorch-ubi9-python-3-11-pull-request.yaml
  .tekton/runtime-cuda-pytorch-ubi9-python-3-11-push.yaml
  .tekton/runtime-cuda-tensorflow-ubi9-python-3-11-pull-request.yaml
  .tekton/runtime-cuda-tensorflow-ubi9-python-3-11-push.yaml
  .tekton/runtime-datascience-ubi9-python-3-11-pull-request.yaml
  .tekton/runtime-datascience-ubi9-python-3-11-push.yaml
  .tekton/runtime-minimal-ubi9-python-3-11-pull-request.yaml
  .tekton/runtime-minimal-ubi9-python-3-11-push.yaml
  Makefile
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  ci/cached-builds/makefile_helper.py
Labels: lgtm, approved, size/xl

#1018 RHOAIENG-20553 - CSS is broken when loading the TensorBoard extension
  jupyter/utils/addons/apply.sh
Labels: lgtm, size/xs

#1021 Follow up to update the commit file properly based on image change
  ci/sha-digest-updater.sh
Labels: lgtm, size/m

#1025 [GHA] Enhance the checks for the kustomization.yaml files
  ci/kustomize.sh
Labels: lgtm, approved, size/m

#1027 Issue opendatahub-io/notebooks#631: cut the ref name to avoid going over 128 character limit for Docker image tag
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, size/xs
