Repository opendatahub-io/notebooks, pull requests merged in 2025-01, with the labels that each got.

#826 feat(deps): add kubeflow-training to workbench images
  codeserver/ubi9-python-3.11/Pipfile
  codeserver/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#828 NO-JIRA: fix(build): use yq to modify kustomization.yaml during deploy targets
  Makefile
Labels: lgtm, approved

#836 Updated notebooks via odh-sync-updater-12711100946 GitHub action
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#840 Updated the runtime-images for 2024a with commit 38cc367
  jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
Labels: approved

#841 Update Imagestream files with new package versions
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved, tide/merge-method-squash

#834 RHOAIENG-16587: fix(test): ensure papermill tests run successfully for all supported notebooks
  .gitignore
  Makefile
  jupyter/datascience/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/intel/ml/ubi9-python-3.11/kustomize/base/statefulset.yaml
  jupyter/intel/ml/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/intel/pytorch/ubi9-python-3.11/kustomize/base/statefulset.yaml
  jupyter/intel/pytorch/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/intel/pytorch/ubi9-python-3.11/test/test_notebook_cpu.ipynb
  jupyter/intel/tensorflow/ubi9-python-3.11/kustomize/base/statefulset.yaml
  jupyter/intel/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/intel/tensorflow/ubi9-python-3.11/test/test_notebook_cpu.ipynb
  jupyter/minimal/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.11/kustomize/base/statefulset.yaml
  jupyter/pytorch/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/rocm/pytorch/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/rocm/tensorflow/ubi9-python-3.11/kustomize/base/statefulset.yaml
  jupyter/rocm/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.11/test/test_notebook.ipynb
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-pytorch-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-tensorflow-notebook-imagestream.yaml
  scripts/test_jupyter_with_papermill.sh
Labels: lgtm, approved

#850 RHOAIENG-17695: chore(ci): capture logs in pytest tests so that we don't have too many debug logs there from passing tests
  .github/workflows/build-notebooks-TEMPLATE.yaml
  tests/conftest.py
Labels: lgtm, approved, size/xs

#835 RHOAIENG-17305: chore(tests): IPv4 compatibility test(s), checking that we did not break the single-stack IPv4 case
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/l

#853 RHOAIENG-8388: rm(intel): fixup to remove one forgotten intel case that's now causing the script to fail
  scripts/test_jupyter_with_papermill.sh
Labels: lgtm, approved, tide/merge-method-squash, size/xs

#854 RHOAIENG-17257: chore(tests): add allure dependency so that we can have fancy html report
  poetry.lock
  pyproject.toml
Labels: lgtm, approved, size/l

#855 RHOAIENG-17257: chore(tests): make the wait for readiness optional
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/xs

#856 RHOAIENG-17257: chore(tests): externalize the default workbench-starting arguments
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/m

#851 [Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release 0.26.0
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved, size/xxl

#860 Update manifests after odh-sync-updater-12886596842 CodeFlare GitHub action ran
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved, size/xs

#857 RHOAIENG-17257: chore(tests): add testcontainers test to check Rmd to PDF rendering in RStudio
  tests/containers/docker_utils.py
  tests/containers/workbenches/rstudio/rstudio_tests.py
Labels: lgtm, approved, tide/merge-method-squash, size/l

#827 RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio
  codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
  codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
  codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
  codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  codeserver/ubi9-python-3.11/run-code-server.sh
  jupyter/minimal/ubi9-python-3.11/start-notebook.sh
  rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
  rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  rstudio/c9s-python-3.11/setup_rstudio.py
Labels: lgtm, approved, ok-to-test, size/m

#861 NO-JIRA: chore(tests/containers): improve docker socket detection, reducing the need for `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`
  tests/containers/conftest.py
Labels: lgtm, approved, size/m

#863 NO-JIRA: chore(tests) Update readme for tests execution + some test fixes for linux env
  README.md
  tests/containers/base_image_test.py
Labels: lgtm, approved, size/m

#849 RHOAIENG-17695: chore(ci): disable ryuk for gha runs and when it actually fails to start (most likely due to rootless podman)
  .github/workflows/build-notebooks-TEMPLATE.yaml
  tests/containers/conftest.py
Labels: lgtm, approved, tide/merge-method-squash, size/s

#866 RHOAIENG-18459: chore(tests/containers/workbenches): listen on single-stack IPv6
  tests/containers/conftest.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, tide/merge-method-squash, size/l

#867 NO-JIRA: chore(poetry.lock) add new pydantic dependency and update existing ones
  poetry.lock
  pyproject.toml
Labels: lgtm, approved, tide/merge-method-squash, size/l

#869 RHOAIENG-18459: chore(tests/containers): handle multiple podman machines and improve debugging output when podman machine is not found
  tests/containers/podman_machine_utils.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, tide/merge-method-squash, size/xs

#870 RHOAIENG-17251: add a test for the proxy env configuration in RStudio + some other minor changes
  tests/containers/workbenches/rstudio/rstudio_test.py
Labels: lgtm, approved, size/m

#872 RHOAIENG-9707: chore(tests/containers): update README.md with testcontainers motivation and lima section
  README.md
  tests/.gitignore
  tests/conftest.py
Labels: lgtm, approved, size/m

#877 Revert "RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio"
  codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
  codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
  codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
  codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  codeserver/ubi9-python-3.11/run-code-server.sh
  jupyter/minimal/ubi9-python-3.11/start-notebook.sh
  rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
  rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  rstudio/c9s-python-3.11/setup_rstudio.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/m

#871 RHOAIENG-9707: chore(tests/containers): check shared objects with ldd
  tests/containers/base_image_test.py
Labels: lgtm, approved, size/l

#873 RHOAIENG-9707: chore(tests/containers): try to install the cowsay package to check the python venv is writable
  tests/containers/base_image_test.py
Labels: lgtm, approved, size/s
