Repository opendatahub-io/notebooks, pull requests merged in 2025-02, with the labels that each got.

#881 RHOAIENG-19036: chore(gha): fix workflow_dispatch invocation
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: good first issue, lgtm, approved, size/s

#878 Reapply "RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio"
  2024b/codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
  2024b/codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
  2024b/codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
  2024b/codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  2024b/codeserver/ubi9-python-3.11/run-code-server.sh
  2024b/jupyter/minimal/ubi9-python-3.11/start-notebook.sh
  2024b/rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
  2024b/rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  2024b/rstudio/c9s-python-3.11/setup_rstudio.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/m

#884 NO-JIRA: chore(tests/containers): detect socket for ryuk's use with rootless podman on macOS
  README.md
  poetry.lock
  pyproject.toml
  tests/containers/conftest.py
  tests/containers/docker_utils.py
  tests/containers/podman_machine_utils.py
  tests/containers/pydantic_schemas/__init__.py
  tests/containers/pydantic_schemas/podman_info.py
  tests/containers/pydantic_schemas/podman_machine_inspect.py
  tests/containers/schemas.py
Labels: lgtm, approved, ok-to-test, size/xl

#886 RHOAIENG-18979: chore(test/containers): check workbench startup logs
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/m

#890 RHOAIENG-19388: fix the transformers version in manifests
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved, size/xs

#891 NO-ISSUE: chore(tests/containers): fix fake fips tests for macOS rootless podman machine
  tests/containers/base_image_test.py
Labels: lgtm, approved, size/s

#889 RHOAIENG-18930: update Jupyterlab package to 4.2.7
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, approved, tide/merge-method-squash, size/xxl

#893 RHOAIENG-18933: removal of the huggingface dependency in our images
  codeserver/ubi9-python-3.11/Pipfile
  codeserver/ubi9-python-3.11/Pipfile.lock
  codeserver/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, approved, tide/merge-method-squash, size/xxl

#902 NO-JIRA: chore(.github/renovate.json): add doc links and disable the managers we are not ready to have around yet
  .github/renovate.json
Labels: lgtm, approved, size/m

#910 ISSUE #883: feat: add `data-testid` attribute for loading spinner
  2024b/jupyter/utils/addons/partial-body.html
  tests/containers/workbenches/jupyterlab/jupyterlab_test.py
Labels: lgtm, approved, ok-to-test, tide/merge-method-squash, size/s

#915 [main] RHOAIENG-11156: chore(tests/containers/jupyterlab): check that the JupyterLab index.html contains the spinner code
  poetry.lock
  pyproject.toml
  tests/containers/workbenches/jupyterlab/__init__.py
  tests/containers/workbenches/jupyterlab/jupyterlab_test.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/m

#919 ISSUE #631: lowercase the image repository name in github actions
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: ok-to-test, size/xs

#918 ISSUE #887: add fixtures to skip test if it's not jupyterlab/codeserver/rstudio image
  tests/containers/conftest.py
  tests/containers/workbenches/jupyterlab/jupyterlab_test.py
  tests/containers/workbenches/rstudio/rstudio_test.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, ok-to-test, size/l

#916 NO-JIRA: chore(tests/containers): report on nginx error messages in logs
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/s

#914 [main] NO-JIRA: chore(tests/containers): detect socket for ryuk's use with rootless podman on macOS
  README.md
  poetry.lock
  pyproject.toml
  tests/containers/conftest.py
  tests/containers/docker_utils.py
  tests/containers/podman_machine_utils.py
  tests/containers/pydantic_schemas/__init__.py
  tests/containers/pydantic_schemas/podman_info.py
  tests/containers/pydantic_schemas/podman_machine_inspect.py
  tests/containers/schemas.py
Labels: lgtm, approved, size/xl

#892 RHOAIENG-18848: chore(tests/containers): initial kubernetes/openshift deployment support
  .github/workflows/build-notebooks-TEMPLATE.yaml
  README.md
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/containers/base_image_test.py
  tests/containers/cancellation_token.py
  tests/containers/kubernetes_utils.py
  tests/containers/socket_proxy.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, ok-to-test, tide/merge-method-squash, size/xxl

#913 [main] Reapply "RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio"
  codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
  codeserver/ubi9-python-3.11/nginx/httpconf/http.conf
  codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
  codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
  codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  codeserver/ubi9-python-3.11/run-code-server.sh
  jupyter/minimal/ubi9-python-3.11/start-notebook.sh
  rstudio/c9s-python-3.11/nginx/httpconf/http.conf
  rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
  rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
  rstudio/c9s-python-3.11/setup_rstudio.py
  tests/containers/workbenches/workbench_image_test.py
Labels: lgtm, approved, size/m

#925 RHOAIENG-20569: Fix the ImageStream manifests with the correct software versions
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
Labels: lgtm, approved, size/s
