Repository opendatahub-io/notebooks, pull requests merged in 2025-09, with the labels that each got.

#2228 NO-JIRA: chore(ci): introduce a `make test` target
  .github/workflows/code-quality.yaml
  Makefile
  README.md
Labels: lgtm, size/s, review-requested

#2233 RHAIENG-304: tests(pytests): add check for the pylock.toml integrity with respect to pyproject.toml
  tests/test_main.py
Labels: lgtm, size/m, review-requested

#2244 RHAIENG-581: filter out and remove from the release notes the automated PR titles generated by Konflux
  .github/release.yml
Labels: size/m, review-requested

#2256 NO-JIRA: only show crio debug info if we actually managed to install crio packages
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: size/xs, review-requested

#2258 NO-JIRA: sudo apt-get install -y --allow-downgrades "cri-o=${CRIO_VERSION}.*"
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, tide/merge-method-squash, size/xs, review-requested

#2112 Issue #2081: Use install -D for robust file copying
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
Labels: lgtm, ok-to-test, size/xs, review-requested

#2270 Add multiarch-push-pipeline config
  .tekton/multiarch-push-pipeline.yaml
  .tekton/odh-base-image-cuda-py311-c9s-push.yaml
  .tekton/odh-base-image-cuda-py312-c9s-push.yaml
  .tekton/odh-base-image-cuda-py312-ubi9-push.yaml
Labels: approved, size/xl, review-requested

#2260 RHAIENG-308, #2242: tests(make): enforce version parity validation between imagestreams
  tests/test_main.py
Labels: lgtm, size/l, review-requested

#2273 Add missing matrix for multiplatform builds
  .tekton/multiarch-push-pipeline.yaml
Labels: size/xs, review-requested

#2272 Replace yum with dnf to have better consistency among the Dockerfiles
  base-images/cuda/12.6/c9s-python-3.11/Dockerfile.cuda
  base-images/cuda/12.6/c9s-python-3.12/Dockerfile.cuda
  base-images/cuda/12.6/ubi9-python-3.12/Dockerfile.cuda
  base-images/rocm/6.2/c9s-python-3.12/Dockerfile.rocm
  base-images/rocm/6.2/ubi9-python-3.12/Dockerfile.rocm
Labels: lgtm, approved, size/m, review-requested

#2277 RHAIENG-308, #2242: tests(make): handle rstudio in a rhds-compatible manner
  tests/manifests.py
  tests/test_main.py
Labels: do-not-merge/work-in-progress, size/s, review-requested

#2278 RHAIENG-816: fix(jupyter/rocm/tensorflow/ubi9-python-3.12): image has outdated jupyterlab and jupyterlab-git packages
  examples/jupyterlab-with-elyra/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pyproject.toml
  tests/test_main.py
Labels: size/m, review-requested

#1513 RHOAIENG-31406: enable Runtime Datascience Images for IBM Z[s390x] (Python 3.12)
  .tekton/odh-pipeline-runtime-datascience-cpu-py312-ubi9-pull-request.yaml
  ci/cached-builds/gen_gha_matrix_jobs.py
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
  runtimes/datascience/ubi9-python-3.12/pylock.toml
  runtimes/datascience/ubi9-python-3.12/pyproject.toml
  scripts/generate_pull_request_pipelineruns.py
Labels: needs-ok-to-test, size/l, s390x

#2330 feat(ppc64le): remove unnecessary build dependency packages and a stray `pip install ml-dtypes`
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
Labels: size/xs

#2342 RHAIENG-308: ref(tests): refactor tests to replace `pytest.fail` with assertions for clearer error reporting in `test_main.py`
  tests/test_main.py
Labels: size/s, review-requested

#2346 RHAIENG-726: add ROCm-based TensorFlow and pipeline runtime images to manifests
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: lgtm, size/xs, review-requested

#2357 RHOAIENG-31964: Add trash-cleanup 0.1.0
  jupyter/datascience/ubi9-python-3.12/pylock.toml
  jupyter/datascience/ubi9-python-3.12/pyproject.toml
  jupyter/minimal/ubi9-python-3.12/pylock.toml
  jupyter/minimal/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/pylock.toml
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/trustyai/ubi9-python-3.12/pylock.toml
  jupyter/trustyai/ubi9-python-3.12/pyproject.toml
Labels: size/m, review-requested

#2385 Update manifest files for 2025b
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/commit-latest.env
  manifests/base/commit.env
  manifests/base/cuda-rstudio-buildconfig.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-llmcompressor-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params-latest.env
  manifests/base/params.env
  manifests/base/rstudio-buildconfig.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
  manifests/base/runtime-datascience-imagestream.yaml
  manifests/base/runtime-minimal-imagestream.yaml
  manifests/base/runtime-pytorch-imagestream.yaml
  manifests/base/runtime-pytorch-llmcompressor-imagestream.yaml
  manifests/base/runtime-rocm-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-tensorflow-imagestream.yaml
  manifests/base/runtime-tensorflow-imagestream.yaml
  manifests/overlays/additional/README.md
  manifests/overlays/additional/codeserver-datascience-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-datascience-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-minimal-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-minimal-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-minimal-rocm-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-pytorch-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-pytorch-rocm-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-tensorflow-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/jupyter-trustyai-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/kustomization.yaml
  manifests/overlays/additional/runtime-datascience-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-minimal-cpu-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-pytorch-llmcompressor-cuda-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-pytorch-rocm-py312-ubi9-imagestream.yaml
  manifests/overlays/additional/runtime-tensorflow-cuda-py312-ubi9-imagestream.yaml
Labels: approved, size/xxl, review-requested

#2448 opendatahub-io/notebooks#2222: tidyup(pyproject.toml): standardize quote style for dependencies in pyproject.toml files
  jupyter/trustyai/ubi9-python-3.12/pyproject.toml
  rstudio/c9s-python-3.11/pyproject.toml
  rstudio/rhel9-python-3.11/pyproject.toml
  runtimes/datascience/ubi9-python-3.12/pyproject.toml
  runtimes/minimal/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pyproject.toml
Labels: lgtm, size/l, review-requested

#2458 Remove revision from output-image opt
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
Labels: lgtm, size/xs, review-requested

#2455 RHAIENG-286: Add base images for CUDA 12.8 and Tekton files for ROCm 6.4
  .tekton/odh-base-image-cuda-12-8-py312-c9s-pull-request.yaml
  .tekton/odh-base-image-cuda-12-8-py312-c9s-push.yaml
  .tekton/odh-base-image-cuda-12-8-py312-ubi9-pull-request.yaml
  .tekton/odh-base-image-cuda-12-8-py312-ubi9-push.yaml
  .tekton/odh-base-image-rocm-6-4-py312-c9s-pull-request.yaml
  .tekton/odh-base-image-rocm-6-4-py312-c9s-push.yaml
  .tekton/odh-base-image-rocm-6-4-py312-ubi9-pull-request.yaml
  .tekton/odh-base-image-rocm-6-4-py312-ubi9-push.yaml
  base-images/cuda/12.8/c9s-python-3.12/Dockerfile.cuda
  base-images/cuda/12.8/cuda-repos/NGC-DL-CONTAINER-LICENSE
  base-images/cuda/12.8/cuda-repos/cuda.repo-amd64
  base-images/cuda/12.8/cuda-repos/cuda.repo-arm64
  base-images/cuda/12.8/ubi9-python-3.12/Dockerfile.cuda
Labels: approved, do-not-merge/hold, size/xl, review-requested

#2462 NO-JIRA: fix(dockerfiles): allow skipping some packages if full upgrade cannot be performed
  codeserver/ubi9-python-3.12/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.rocm
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.cpu
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.cuda
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.rocm
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  scripts/dockerfile_fragments.py
Labels: lgtm, approved, size/l, review-requested

#2461 Add a gha that updates and commits the image tags automatically
  .github/workflows/update-tags.yaml
Labels: lgtm, approved, size/m, review-requested

#2464 RHAIENG-1057: (chore): open PR while image tag update
  .github/workflows/update-tags.yaml
Labels: lgtm, approved, size/m, review-requested

#1975 RHAIENG-406: tests(manual): add `tensorflow-test.ipynb`
  tests/manual/tensorflow-test.ipynb
Labels: size/l, review-requested

#2492 fix `.tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-push` pipeline's service account name to match the component
  .tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-push.yaml
Labels: lgtm, approved, size/xs, review-requested

#2111 NO-JIRA: tests(fix): remove unused tensorboard import (fixes #2077)
  jupyter/rocm/tensorflow/ubi9-python-3.12/test/test_notebook.ipynb
Labels: lgtm, approved, ok-to-test, tide/merge-method-squash, size/m, review-requested

#2493 chore: bump `codeflare-sdk` to v0.31.1 across all pyproject.toml files
  jupyter/datascience/ubi9-python-3.12/pylock.toml
  jupyter/datascience/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/trustyai/ubi9-python-3.12/pylock.toml
  jupyter/trustyai/ubi9-python-3.12/pyproject.toml
  runtimes/datascience/ubi9-python-3.12/pylock.toml
  runtimes/datascience/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch/ubi9-python-3.12/pylock.toml
  runtimes/pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pylock.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pyproject.toml
  runtimes/tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/tensorflow/ubi9-python-3.12/pyproject.toml
Labels: lgtm, size/m, review-requested

#2496 Fix path on the build-arg-file field
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
Labels: lgtm, size/xs, review-requested

#2503 s390x(runtime-datascience): fix pyarrow build in Dockerfile.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
Labels: lgtm, approved, size/m, review-requested

#2498 Replace supervisord and fcgi and supervisord with httpd
  codeserver/ubi9-python-3.12/Dockerfile.cpu
  codeserver/ubi9-python-3.12/httpd/codeserver-cgi.conf
  codeserver/ubi9-python-3.12/httpd/httpd.conf
  codeserver/ubi9-python-3.12/nginx/serverconf/proxy.conf.template
  codeserver/ubi9-python-3.12/nginx/serverconf/proxy.conf.template_nbprefix
  codeserver/ubi9-python-3.12/run-code-server.sh
  codeserver/ubi9-python-3.12/supervisord/supervisord.conf
Labels: lgtm, approved, size/l, review-requested

#2508 RHAIENG-974: enable missing module `mod_mime.so`
  codeserver/ubi9-python-3.12/httpd/httpd.conf
Labels: lgtm, approved, size/xs, review-requested

#2513 RHAIENG-1023: fix(rstudio): update the esbuild inside of rstudio's installation as it was done in the poc
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
  rstudio/utils/README.md
  rstudio/utils/cve_remediation.sh
  rstudio/utils/package-lock.json
  rstudio/utils/package.json
Labels: lgtm, size/xl, review-requested

#2505 RHAIENG-608: Update all runtimes imagestream names with new naming format
  manifests/base/runtime-datascience-imagestream.yaml
  manifests/base/runtime-minimal-imagestream.yaml
  manifests/base/runtime-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-tensorflow-imagestream.yaml
  manifests/base/runtime-tensorflow-imagestream.yaml
Labels: lgtm, approved, size/m, review-requested

#2414 RHAIENG-286: 2025b images package upgrade
  Makefile
  ci/package_versions.py
  codeserver/ubi9-python-3.12/pylock.toml
  codeserver/ubi9-python-3.12/pyproject.toml
  jupyter/datascience/ubi9-python-3.12/pylock.toml
  jupyter/datascience/ubi9-python-3.12/pyproject.toml
  jupyter/minimal/ubi9-python-3.12/build-args/cuda.conf
  jupyter/minimal/ubi9-python-3.12/pylock.toml
  jupyter/minimal/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/build-args/cuda.conf
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/pylock.toml
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch/ubi9-python-3.12/build-args/cuda.conf
  jupyter/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/build-args/rocm.conf
  jupyter/rocm/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/build-args/rocm.conf
  jupyter/rocm/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/tensorflow/ubi9-python-3.12/build-args/cuda.conf
  jupyter/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/trustyai/ubi9-python-3.12/pylock.toml
  jupyter/trustyai/ubi9-python-3.12/pyproject.toml
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-llmcompressor-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  rstudio/c9s-python-3.11/pylock.toml
  rstudio/c9s-python-3.11/pyproject.toml
  rstudio/rhel9-python-3.11/pylock.toml
  rstudio/rhel9-python-3.11/pyproject.toml
  runtimes/datascience/ubi9-python-3.12/pylock.toml
  runtimes/datascience/ubi9-python-3.12/pyproject.toml
  runtimes/minimal/ubi9-python-3.12/pylock.toml
  runtimes/minimal/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/pylock.toml
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch/ubi9-python-3.12/pylock.toml
  runtimes/pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pylock.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pyproject.toml
  runtimes/tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/tensorflow/ubi9-python-3.12/pyproject.toml
  tests/test_main.py
Labels: approved, trivy-scan, size/xxl, review-requested

#2518 RHAIENG-1193: codeserver(repo): update vscode extensions for 2025b release from Open VSX Registry
  codeserver/Extensions.md
  codeserver/ubi9-python-3.12/Dockerfile.cpu
  codeserver/ubi9-python-3.12/utils/ms-python.debugpy-2025.4.1@linux-x64.vsix
  codeserver/ubi9-python-3.12/utils/ms-python.python-2025.14.0.vsix
  codeserver/ubi9-python-3.12/utils/ms-python.python-2025.2.0.vsix
  codeserver/ubi9-python-3.12/utils/ms-toolsai.jupyter-2025.2.0.vsix
  codeserver/ubi9-python-3.12/utils/ms-toolsai.jupyter-2025.8.0.vsix
  codeserver/ubi9-python-3.12/utils/ms-toolsai.jupyter-keymap-1.1.2.vsix
  codeserver/ubi9-python-3.12/utils/ms-toolsai.jupyter-renderers-1.1.0.vsix
  codeserver/ubi9-python-3.12/utils/ms-toolsai.vscode-jupyter-cell-tags-0.1.9.vsix
  codeserver/ubi9-python-3.12/utils/ms-toolsai.vscode-jupyter-slideshow-0.1.6.vsix
Labels: size/m, review-requested

#2528 Make codeserver multiarch supported and change the vm
  .tekton/odh-workbench-codeserver-datascience-cpu-py312-ubi9-push.yaml
Labels: lgtm, size/xs, review-requested

#2538 NO-JIRA: chore(ci): extract k8s setup into a composite action
  .github/actions/free-up-disk-space/action.yml
  .github/actions/provision-k8s/action.yml
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/test-provision-k8s.yaml
Labels: lgtm, size/l, review-requested

#2543 Add tekton pipelines for rstudio py312
  .tekton/odh-workbench-rstudio-minimal-cpu-py312-c9s-pull-request.yaml
  .tekton/odh-workbench-rstudio-minimal-cpu-py312-c9s-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cuda-py312-c9s-pull-request.yaml
  .tekton/odh-workbench-rstudio-minimal-cuda-py312-c9s-push.yaml
Labels: lgtm, size/l, review-requested

#2544 RHAIENG-1284: fix(Dockerfiles) libcrypt.so.1 not found in runtime-datascience-rocm-tensorflow-ubi9-python-3.12 image
  runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.rocm
Labels: lgtm, approved, size/xs, review-requested
