Repository opendatahub-io/notebooks, pull requests merged in 2025-03, with the labels that each got.

#934 NO-JIRA: chore(Makefile): remove `BUILD_DEPENDENT_IMAGES` option
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  README.md
Labels: lgtm, approved, size/s

#936 RHOAIENG-16384: Fix build error of Rcpp for R 4.4.2
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
Labels: lgtm, approved, ok-to-test, size/xs

#941 RHOAIENG-18400: chore(konflux): restrict triggering only for the opendatahub-io/notebooks repository
  .tekton/jupyter-minimal-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
Labels: lgtm, approved, size/xs

#942 RHOAIENG-19048: chore(gha): remove the upfront workflow generation script
  .github/workflows/build-notebooks-push.yaml
  .github/workflows/build-notebooks.yaml
  Makefile
  ci/cached-builds/gen_gha_matrix_jobs.py
  ci/generate_code.sh
Labels: lgtm, approved, size/l

#940 JIRA 19497: feat(deps): include skopeo in all workbench images
  codeserver/ubi9-python-3.11/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  runtimes/datascience/ubi9-python-3.11/Dockerfile.cpu
  runtimes/minimal/ubi9-python-3.11/Dockerfile.cpu
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.cuda
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.rocm
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  tests/containers/base_image_test.py
Labels: lgtm, approved, size/l

#937 RHOAIENG-19908: Install tf2onnx from dev-packages for overriding protobuf
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/utils/python_dsl_template.patch
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/utils/python_dsl_template.patch
Labels: lgtm, approved, size/xxl

#947 NO-JIRA: chore(konflux): introduce image retention on pushed images
  .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
Labels: lgtm, approved, size/xs

#948 RHOAIENG-19051: chore(Makefile): remove dependency on `bin/buildinputs` for running image tests
  Makefile
Labels: lgtm, approved, size/xs

#955 RHOAIENG-20088: chore(ci/check-params-env.sh|check-runtime-images.sh)
  ci/check-params-env.sh
  ci/check-runtime-images.sh
Labels: lgtm, approved, size/s

#903 RHOAIENG-18400: chore(konflux): create helper scripts to generate konflux configs
  .tekton/image-registry.yaml
  .tekton/jupyter-minimal-ubi9-python-3-11-pull-request.yaml
  .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
  Makefile
  ci/cached-builds/gha_pr_changed_files.py
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  ci/cached-builds/konflux_generate_component_definitions.py
Labels: lgtm, approved, tide/merge-method-squash, size/xxl

#961 NO-JIRA: chore(.tekton): remove dead code in konflux_generate_component_build_pipelines.py
  ci/cached-builds/konflux_generate_component_build_pipelines.py
Labels: lgtm, approved, size/m

#962 RHOAIENG-18400: chore(.tekton/): implement computation of `"pipelinesascode.tekton.dev/on-cel-expression"` values
  .tekton/jupyter-minimal-ubi9-python-3-11-pull-request.yaml
  ci/cached-builds/konflux_generate_component_build_pipelines.py
  scripts/__init__.py
  scripts/sandbox.py
Labels: lgtm, approved, size/m

#946 RHOAIENG-19478, RHOAIENG-19715, RHOAIENG-19485 - Explore versions compatibility, upgrade Jupyter packages and upgrade Runtime images
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/minimal/ubi9-python-3.11/Pipfile
  runtimes/minimal/ubi9-python-3.11/Pipfile.lock
  runtimes/minimal/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, approved, tide/merge-method-squash, size/xxl

#944 (case 2) Add the runtime-images COPY cmd back on DS notebook
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  manifests/base/kustomization.yaml
Labels: lgtm, approved, tide/merge-method-squash, size/xs

#970 NO-JIRA: chore(gha): switch image build to ubuntu-24.04 as there is more disk space available
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: lgtm, approved, size/xs

#949 chore(cuda): Upgrade all cuda-related IDE workbenches to CUDA 12.6
  ci/check-params-env.sh
  cuda/NGC-DL-CONTAINER-LICENSE
  cuda/c9s-python-3.11/cuda.repo-arm64
  cuda/cuda.repo-x86_64
  cuda/ubi9-python-3.11/NGC-DL-CONTAINER-LICENSE
  cuda/ubi9-python-3.11/cuda.repo-x86_64
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/kustomize/components/accelerator/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.11/kustomize/components/accelerator/pod-patch.yaml
  jupyter/pytorch/ubi9-python-3.11/kustomize/overlays/accelerator/cuda/kustomization.yaml
  jupyter/pytorch/ubi9-python-3.11/kustomize/overlays/accelerator/cuda/pod-patch.yaml
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  manifests/base/commit.env
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/params.env
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/c9s-python-3.11/Pipfile
  rstudio/c9s-python-3.11/Pipfile.lock
  rstudio/c9s-python-3.11/kustomize/components/accelerator/kustomization.yaml
  rstudio/c9s-python-3.11/kustomize/components/accelerator/pod-patch.yaml
  rstudio/c9s-python-3.11/kustomize/overlays/accelerator/cuda/kustomization.yaml
  rstudio/c9s-python-3.11/kustomize/overlays/accelerator/cuda/pod-patch.yaml
  rstudio/c9s-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.cuda
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/kustomize/components/accelerator/kustomization.yaml
  runtimes/pytorch/ubi9-python-3.11/kustomize/components/accelerator/pod-patch.yaml
  runtimes/pytorch/ubi9-python-3.11/kustomize/overlays/accelerator/cuda/kustomization.yaml
  runtimes/pytorch/ubi9-python-3.11/kustomize/overlays/accelerator/cuda/pod-patch.yaml
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
  scripts/test_jupyter_with_papermill.sh
Labels: lgtm, approved, tide/merge-method-squash, size/xxl

#956 Update Rocm base image for release 2025a
  jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.rocm
Labels: lgtm, approved, size/m

#965 feat(upgrade): bi-annual RStudio package update
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/c9s-python-3.11/install_packages.R
  rstudio/c9s-python-3.11/kustomize/components/accelerator/pod-patch.yaml
  rstudio/c9s-python-3.11/kustomize/overlays/accelerator/cuda/pod-patch.yaml
Labels: lgtm, approved, size/l

#972 Update remaining imagestreams and shift the n params as n-1
  ci/check-params-env.sh
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/commit.env
  manifests/base/commit.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  manifests/base/rstudio-gpu-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
Labels: lgtm, approved, tide/merge-method-squash, size/l

#973 ISSUE #971: chore(gha): switch from ext4 to btrfs with compression and add log printing for the future
  .github/workflows/build-notebooks-TEMPLATE.yaml
  ci/cached-builds/gha_lvm_overlay.sh
Labels: lgtm, approved, tide/merge-method-rebase, size/m

#981 NO-ISSUE: chore(ci): fix expected image names in params.env check
  ci/check-params-env.sh
Labels: lgtm, approved, size/s

#983 NO-ISSUE: fix the manifest definitions software versions for images
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/rstudio-notebook-imagestream.yaml
Labels: lgtm, approved, size/xs

#984 NO-JIRA: fix(ci): update the way we check for the rocm version
  ci/check-software-versions.py
Labels: lgtm, approved, size/xs

#987 ISSUE-922: chore(tests/containers): implement retry if port-forwarding fails
  tests/containers/kubernetes_utils.py
  tests/containers/socket_proxy.py
Labels: lgtm, approved, size/m

#989 NO-JIRA: chore(tests/): fix running rstudio rhel9 Makefile image tests
  Makefile
  ci/cached-builds/make_test.py
Labels: approved, size/m

#990 NO-JIRA: fix(manifests/): torch version in `jupyter-rocm-pytorch-notebook-imagestream.yaml`
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
Labels: lgtm, approved, size/xs

#992 RHOAIENG-21740: Perform filesystem permission check on images
  tests/containers/base_image_test.py
  tests/containers/conftest.py
  tests/containers/utils.py
Labels: lgtm, approved, size/m

#993 RHOAIENG-22439: fix(manifests/rstudio): dismantle the broken RStudio BuildConfig chain and build the image directly
  manifests/base/cuda-rstudio-buildconfig.yaml
Labels: lgtm, approved, size/m
