Repository opendatahub-io/notebooks, pull requests merged in 2025-08, with the labels that each got.

#1518 Update `test_jupyter_with_papermill.sh` script for python312
  scripts/test_jupyter_with_papermill.sh
Labels: lgtm, ok-to-test, size/m

#1572 RHOAIENG-12554, RHOAIENG-12195: add TrustyAI `README.md` with TMaRCo detoxification details and required dependencies justification
  jupyter/trustyai/README.md
Labels: lgtm, approved, size/xs

#1573 chore: Update Image name retrieved field to fix the params-validator
  ci/check-params-env.sh
Labels: lgtm, approved, size/xs

#1584 Simplify piplock-renewal workflow by reordering commit and pull steps
  .github/workflows/piplock-renewal.yaml
Labels: lgtm, size/s

#1600 Issue opendatahub-io/notebooks#1598: RHAIENG-337: add support for `pytorch+llmcompressor` variants to Makefile for jupyter and runtime CUDA images
  Makefile
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
Labels: tide/merge-method-squash, size/m

#1599 Issue opendatahub-io/notebooks#385: refactor(Dockerfile.cuda): clean up commented-out CUDA and cudnn9 installation
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
Labels: lgtm, size/l

#1634 Issue #1631: fix(scripts/buildinputs/) validate `TARGETPLATFORM` environment variable
  scripts/buildinputs/buildinputs.go
Labels: lgtm, approved, tide/merge-method-squash, size/xs

#1239 [RHOAIENG-17006] Converted all dockerfiles and requirements.txt file to work with uv
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.12/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.rocm
  jupyter/minimal/ubi9-python-3.12/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.rocm
  jupyter/rocm/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.12/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.cpu
  jupyter/trustyai/ubi9-python-3.12/requirements.txt
Labels: lgtm, approved, ok-to-test, size/xxl

#1520 [RHOAIENG-17006] document the migration of dependencies from pipenv to uv
  docs/uv-guide.md
Labels: size/l

#1689 docs(examples): hadolint insists on --no-cache-dir, even though we already take care of this in s2i env variables
  examples/jupyterlab-with-elyra/Dockerfile
Labels: size/xs

#1635 feat(ci): add `dockerfile_fragments.py` to `ci/generate_code.sh` to ensure code is in sync
  ci/generate_code.sh
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Dockerfile.cuda
  scripts/dockerfile_fragments.py
Labels: lgtm, tide/merge-method-squash, size/s

#968 RHOAIENG-21690: chore(Dockerfiles): augument `micropipenv` with `uv` for faster package installs
  codeserver/ubi9-python-3.11/Dockerfile.cpu
  codeserver/ubi9-python-3.12/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
  runtimes/datascience/ubi9-python-3.11/Dockerfile.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
  runtimes/minimal/ubi9-python-3.11/Dockerfile.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.cpu
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.cuda
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.rocm
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.rocm
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.cuda
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
Labels: lgtm, tide/merge-method-squash, size/l

#1696 RHOAIENG-11679: update kustomization.yaml to replace deprecated `commonLabels` with `labels` using `includeSelectors` structure
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/kustomize/base/kustomization.yaml
Labels: lgtm, size/xs

#1714 NO-JIRA: workflows: allow parallelism with concurrency groups by adding Python version matrix in `piplock-renewal.yaml`
  .github/workflows/piplock-renewal.yaml
Labels: lgtm, tide/merge-method-squash, size/xs

#1783 Rename accelerator_flavor to keep both local and global variables
  scripts/test_jupyter_with_papermill.sh
Labels: lgtm, size/xs

#1815 Update version of Tekton build images
  .tekton/odh-pipeline-runtime-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py312-ubi9-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cpu-py311-c9s-push.yaml
  .tekton/odh-workbench-rstudio-minimal-cuda-py311-c9s-push.yaml
Labels: size/m

#1784 NO-JIRA: ensure empty lines are skipped while processing env files in `check-params-env.sh`
  ci/check-params-env.sh
Labels: lgtm, size/xs

#1768 NO-JIRA: chore(gha): add workflow to label PRs with "review-requested" on creation
  .github/workflows/notify-team-to-review-pr.yml
Labels: tide/merge-method-squash, size/s, review-requested

#1881 NO-JIRA: bump TensorFlow and Tensorboard versions to 2.19 in `jupyter-tensorflow-cuda-py312-ubi9` imagestream YAML
  manifests/overlays/additional/jupyter-tensorflow-cuda-py312-ubi9-imagestream.yaml
Labels: size/xs, review-requested

#1878 Issue opendatahub-io/notebooks#1598: RHAIENG-337: add `pytorch+llmcompressor` runtime to Makefile for `refresh-pipfilelock-files`
  Makefile
  codeserver/ubi9-python-3.11/Pipfile.lock
  codeserver/ubi9-python-3.11/requirements.txt
  codeserver/ubi9-python-3.12/Pipfile.lock
  codeserver/ubi9-python-3.12/requirements.txt
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/datascience/ubi9-python-3.12/Pipfile.lock
  jupyter/datascience/ubi9-python-3.12/requirements.txt
  jupyter/minimal/ubi9-python-3.11/Pipfile.lock
  jupyter/minimal/ubi9-python-3.11/requirements.txt
  jupyter/minimal/ubi9-python-3.12/Pipfile.lock
  jupyter/minimal/ubi9-python-3.12/requirements.txt
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch+llmcompressor/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.12/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.12/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.12/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.12/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.12/Pipfile.lock
  runtimes/datascience/ubi9-python-3.12/requirements.txt
  runtimes/minimal/ubi9-python-3.12/Pipfile.lock
  runtimes/minimal/ubi9-python-3.12/requirements.txt
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch+llmcompressor/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.12/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.12/requirements.txt
Labels: tide/merge-method-squash, size/xxl

#1908 NO-JIRA: Update params hashes
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: size/s

#1914 NO-JIRA: fix `notify-team-to-review-pr.yml` by using `on:` `pull_request_target:` to resolve 403 error
  .github/workflows/notify-team-to-review-pr.yml
Labels: lgtm, tide/merge-method-squash, size/xs

#1997 RHAIENG-406: tests(manual): add detailed documentation for testing Elyra notebook runtime images in RHOAI
  tests/manual/runtime_elyra/README.md
  tests/manual/runtime_elyra/images/img_001_540124f9328693a1.png
  tests/manual/runtime_elyra/images/img_002_a67649a3481921a0.png
  tests/manual/runtime_elyra/images/img_003_93b2f00a24a50ba5.png
  tests/manual/runtime_elyra/images/img_004_f6fb213b7c025110.png
  tests/manual/runtime_elyra/images/img_005_79f45424b074b771.png
  tests/manual/runtime_elyra/images/img_006_54fbd228f8a42606.png
  tests/manual/runtime_elyra/images/img_007_a6379b0293c51668.png
  tests/manual/runtime_elyra/images/img_008_98637cabac3e7dc0.png
  tests/manual/runtime_elyra/images/img_009_9383a8eeecdb4f05.png
  tests/manual/runtime_elyra/images/img_010_ab640941c0b73fd9.png
  tests/manual/runtime_elyra/images/img_011_6a98825cc08b7287.png
  tests/manual/runtime_elyra/images/img_012_415f8c4792ae6f30.png
  tests/manual/runtime_elyra/images/img_013_7b7d198ba42ecbf7.png
  tests/manual/runtime_elyra/images/img_014_d319253a7b58e7af.png
  tests/manual/runtime_elyra/images/img_015_f0ea7c430c130289.png
  tests/manual/runtime_elyra/images/img_016_7cabbcc983333981.png
  tests/manual/runtime_elyra/images/img_017_e402e2ff16aec9ef.png
  tests/manual/runtime_elyra/images/img_018_f544d157b449cbde.png
  tests/manual/runtime_elyra/images/img_019_9b2fd9d3d3ab3a31.png
  tests/manual/runtime_elyra/images/img_020_4279d51e65f85947.png
  tests/manual/runtime_elyra/images/img_021_677be6ce28801bad.png
  tests/manual/runtime_elyra/images/img_022_659e781dc93b07bf.png
Labels: tide/merge-method-squash, size/l, review-requested

#2000 RHAIENG-540: bump Jupyter Core to 5.8.1 Across All Runtime Images
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.12/Pipfile
  runtimes/datascience/ubi9-python-3.12/Pipfile.lock
  runtimes/datascience/ubi9-python-3.12/requirements.txt
  runtimes/minimal/ubi9-python-3.11/Pipfile
  runtimes/minimal/ubi9-python-3.11/Pipfile.lock
  runtimes/minimal/ubi9-python-3.11/requirements.txt
  runtimes/minimal/ubi9-python-3.12/Pipfile
  runtimes/minimal/ubi9-python-3.12/Pipfile.lock
  runtimes/minimal/ubi9-python-3.12/requirements.txt
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Pipfile
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Pipfile.lock
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.12/Pipfile
  runtimes/pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.12/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.12/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.12/Pipfile
  runtimes/tensorflow/ubi9-python-3.12/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.12/requirements.txt
Labels: size/xl, review-requested

#2107 NO-JIRA: fix update-commit-latest-env.py to work with multiarch manifests
  scripts/update-commit-latest-env.py
Labels: lgtm, size/xs, review-requested

#2109 NO-JIRA: sort environment variables alphabetically in `update-commit-latest-env.py`
  scripts/update-commit-latest-env.py
Labels: lgtm, size/xs, review-requested

#2143 NO-JIRA: update `pr-merge-image-delete` workflow to remove Python 3.11 images and add 3.12 versions
  .github/workflows/pr-merge-image-delete.yml
Labels: lgtm, approved, size/m

#2176 opendatahub-io/notebooks#2166: chore(typofix): update Dockerfile to use CUDA cudnn9 and correct documentation link
  rstudio/rhel9-python-3.11/Dockerfile.cuda
Labels: size/xs, review-requested

#2179 opendatahub-io/notebooks#2178: fix(ci): add missing `cri-tools` dependency in build-notebooks workflow
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: tide/merge-method-squash, size/xs, review-requested

#2174 NO-JIRA: resume testing of cuda-based rstudio images in GitHub Actions
  Makefile
Labels: tide/merge-method-squash, size/xs, review-requested

#2182 RHAIENG-304, RHAIENG-785: remove all `requirements.txt` and `Pipfile.lock`
  codeserver/ubi9-python-3.12/Pipfile
  codeserver/ubi9-python-3.12/Pipfile.lock
  codeserver/ubi9-python-3.12/requirements.txt
  jupyter/datascience/ubi9-python-3.12/Pipfile
  jupyter/datascience/ubi9-python-3.12/Pipfile.lock
  jupyter/datascience/ubi9-python-3.12/requirements.txt
  jupyter/minimal/ubi9-python-3.12/Pipfile
  jupyter/minimal/ubi9-python-3.12/Pipfile.lock
  jupyter/minimal/ubi9-python-3.12/requirements.txt
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Pipfile
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/requirements.txt
  jupyter/pytorch/ubi9-python-3.12/Pipfile
  jupyter/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.12/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.12/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.12/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.12/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.12/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.12/requirements.txt
  jupyter/tensorflow/ubi9-python-3.12/Pipfile
  jupyter/tensorflow/ubi9-python-3.12/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.12/requirements.txt
  jupyter/trustyai/ubi9-python-3.12/Pipfile
  jupyter/trustyai/ubi9-python-3.12/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.12/requirements.txt
  rstudio/c9s-python-3.11/Pipfile
  rstudio/c9s-python-3.11/Pipfile.lock
  rstudio/c9s-python-3.11/requirements.txt
  rstudio/rhel9-python-3.11/Pipfile
  rstudio/rhel9-python-3.11/Pipfile.lock
  rstudio/rhel9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.12/Pipfile
  runtimes/datascience/ubi9-python-3.12/Pipfile.lock
  runtimes/datascience/ubi9-python-3.12/requirements.txt
  runtimes/minimal/ubi9-python-3.12/Pipfile
  runtimes/minimal/ubi9-python-3.12/Pipfile.lock
  runtimes/minimal/ubi9-python-3.12/requirements.txt
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Pipfile
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Pipfile.lock
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/requirements.txt
  runtimes/pytorch/ubi9-python-3.12/Pipfile
  runtimes/pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.12/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.12/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.12/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.12/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.12/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.12/requirements.txt
  runtimes/tensorflow/ubi9-python-3.12/Pipfile
  runtimes/tensorflow/ubi9-python-3.12/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.12/requirements.txt
Labels: size/xxl, review-requested

#2185 Issue #2157: chore(Dockerfiles): replace yum with dnf consistently across UBI9 Dockerfiles
  codeserver/ubi9-python-3.12/Dockerfile.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.rocm
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.rocm
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.cuda
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.rocm
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
Labels: size/l, review-requested

#2195 Re-enable llmCompressor for ODH availability
  manifests/base/params-latest.env
  manifests/overlays/additional/kustomization.yaml
Labels: lgtm, size/m, review-requested

#2175 NO-JIRA: bump default Python version in `refresh-pipfilelock-files` Makefile task from 3.11 to 3.12
  Makefile
Labels: lgtm, approved, tide/merge-method-squash, size/xs, review-requested

#2223 RHAIENG-304, RHAIENG-786: chore(ci): don't activate the uv env in `security.yaml`, turns out rabbit was on the right track
  .github/workflows/security.yaml
Labels: size/s, review-requested

#2224 Issue #2199: chore(ci): change build-notebooks workflow to use activation key for Red Hat subscription registration instead of storing entitlement certificates
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: size/s, review-requested
